From Coq Require Import Lists.List.
From Coq Require Import Bool.Bool.
From Coq Require Import Arith.PeanoNat.
From Coq Require Import Lia.
From Coq Require Import Logic.ClassicalDescription.
From Coq Require Import Logic.ProofIrrelevance.

Import ListNotations.
Set Implicit Arguments.
Unset Automatic Proposition Inductives.

Module ErrorReflectionTheory1528.

(** Sections 0--2: finite sequences and the comparison-dimension algebra. *)

Definition nonempty {A : Type} (xs : list A) : Prop := xs <> [].

Fixpoint adjacent {A : Type} (R : A -> A -> Prop) (xs : list A) : Prop :=
  match xs with
  | [] => True
  | x :: xs' =>
      match xs' with
      | [] => True
      | y :: _ => R x y /\ adjacent R xs'
      end
  end.

Inductive DimTerm (AtomDim : Type) : Type :=
| DAtom : AtomDim -> DimTerm AtomDim
| DTensor : DimTerm AtomDim -> DimTerm AtomDim -> DimTerm AtomDim
| DOption : DimTerm AtomDim -> DimTerm AtomDim -> DimTerm AtomDim
| DSeq : DimTerm AtomDim -> DimTerm AtomDim -> DimTerm AtomDim.

Arguments DAtom {AtomDim} _.
Arguments DTensor {AtomDim} _ _.
Arguments DOption {AtomDim} _ _.
Arguments DSeq {AtomDim} _ _.

(** The least equivalence relation containing [Theta] and closed under all
    three constructors. This is the setoid presentation of DimTerm/Theta. *)
Inductive dim_congruence {AtomDim : Type}
    (Theta : DimTerm AtomDim -> DimTerm AtomDim -> Prop)
    : DimTerm AtomDim -> DimTerm AtomDim -> Prop :=
| DC_refl : forall x, dim_congruence Theta x x
| DC_theta : forall x y, Theta x y -> dim_congruence Theta x y
| DC_sym : forall x y,
    dim_congruence Theta x y -> dim_congruence Theta y x
| DC_trans : forall x y z,
    dim_congruence Theta x y ->
    dim_congruence Theta y z ->
    dim_congruence Theta x z
| DC_tensor : forall x x' y y',
    dim_congruence Theta x x' ->
    dim_congruence Theta y y' ->
    dim_congruence Theta (DTensor x y) (DTensor x' y')
| DC_option : forall x x' y y',
    dim_congruence Theta x x' ->
    dim_congruence Theta y y' ->
    dim_congruence Theta (DOption x y) (DOption x' y')
| DC_seq : forall x x' y y',
    dim_congruence Theta x x' ->
    dim_congruence Theta y y' ->
    dim_congruence Theta (DSeq x y) (DSeq x' y').

Lemma dim_tensor_well_defined :
  forall (AtomDim : Type)
         (Theta : DimTerm AtomDim -> DimTerm AtomDim -> Prop)
         x x' y y',
    dim_congruence Theta x x' ->
    dim_congruence Theta y y' ->
    dim_congruence Theta (DTensor x y) (DTensor x' y').
Proof.
  intros AtomDim Theta x x' y y' Hx Hy.
  exact (DC_tensor Hx Hy).
Qed.

Lemma dim_option_well_defined :
  forall (AtomDim : Type)
         (Theta : DimTerm AtomDim -> DimTerm AtomDim -> Prop)
         x x' y y',
    dim_congruence Theta x x' ->
    dim_congruence Theta y y' ->
    dim_congruence Theta (DOption x y) (DOption x' y').
Proof.
  intros AtomDim Theta x x' y y' Hx Hy.
  exact (DC_option Hx Hy).
Qed.

Lemma dim_seq_well_defined :
  forall (AtomDim : Type)
         (Theta : DimTerm AtomDim -> DimTerm AtomDim -> Prop)
         x x' y y',
    dim_congruence Theta x x' ->
    dim_congruence Theta y y' ->
    dim_congruence Theta (DSeq x y) (DSeq x' y').
Proof.
  intros AtomDim Theta x x' y y' Hx Hy.
  exact (DC_seq Hx Hy).
Qed.

Record AtomicDimensionBasis : Type := {
  AtomDim : Type;
  a_bind : AtomDim;
  a_rule : AtomDim;
  a_model : AtomDim;
  a_truth : AtomDim;
  a_boundary : AtomDim;
  five_atoms_distinct :
    NoDup [a_bind; a_rule; a_model; a_truth; a_boundary]
}.

Definition Bind (D : AtomicDimensionBasis) : DimTerm (AtomDim D) :=
  DAtom (a_bind D).
Definition RuleDim (D : AtomicDimensionBasis) : DimTerm (AtomDim D) :=
  DAtom (a_rule D).
Definition ModelDim (D : AtomicDimensionBasis) : DimTerm (AtomDim D) :=
  DAtom (a_model D).
Definition TruthDim (D : AtomicDimensionBasis) : DimTerm (AtomDim D) :=
  DAtom (a_truth D).
Definition BoundaryDim (D : AtomicDimensionBasis) : DimTerm (AtomDim D) :=
  DAtom (a_boundary D).

(** Sections 1 and 3: the bottom environment and the ten-component
    comparison-reflective error calculus. *)

Record BottomEnvironment : Type := {
  Correct : Type;
  Error : Type;
  Rule : Type;
  Boundary : Type;
  correct_step : Correct -> Correct -> Prop;
  ordinary_error_step : Error -> Error -> Prop
}.

Record ComparisonCalculus : Type := {
  base : BottomEnvironment;

  (** A comparison calculus does not receive an arbitrary dimension carrier.
      Its dimensions are exactly the terms of the explicitly presented
      algebra, read modulo the least congruence generated by [dimension_equations].
      Rocq has no native quotient type, so equality in the quotient is carried
      by [dim_congruence] below and every relation is required to respect it. *)
  dimension_basis : AtomicDimensionBasis;
  dimension_equations :
    DimTerm (AtomDim dimension_basis) ->
    DimTerm (AtomDim dimension_basis) -> Prop;

  Witness : Type;
  Diff : DimTerm (AtomDim dimension_basis) ->
         Correct base -> Error base -> Witness -> Prop;
  Next : DimTerm (AtomDim dimension_basis) -> Correct base -> Error base ->
         Correct base -> Error base -> Prop;
  InvDelta : DimTerm (AtomDim dimension_basis) ->
             Correct base -> Error base -> Witness -> Prop;
  InvBack : DimTerm (AtomDim dimension_basis) ->
            Correct base -> Error base -> Witness ->
            Boundary base -> Rule base -> Prop;
  PresDelta : DimTerm (AtomDim dimension_basis) ->
              DimTerm (AtomDim dimension_basis) ->
              Correct base -> Error base -> Witness ->
              Correct base -> Error base -> Witness -> Prop;
  PresBack : DimTerm (AtomDim dimension_basis) ->
             DimTerm (AtomDim dimension_basis) ->
             Correct base -> Error base -> Witness ->
             Boundary base -> Rule base ->
             Correct base -> Error base -> Witness ->
             Boundary base -> Rule base -> Prop;
  Back : DimTerm (AtomDim dimension_basis) ->
         Correct base -> Error base -> Boundary base -> Rule base -> Prop;

  diff_respects_dimension : forall k k' c e w,
    dim_congruence dimension_equations k k' ->
    (Diff k c e w <-> Diff k' c e w);
  next_respects_dimension : forall k k' c e c' e',
    dim_congruence dimension_equations k k' ->
    (Next k c e c' e' <-> Next k' c e c' e');
  inv_delta_respects_dimension : forall k k' c e w,
    dim_congruence dimension_equations k k' ->
    (InvDelta k c e w <-> InvDelta k' c e w);
  inv_back_respects_dimension : forall k k' c e w b r,
    dim_congruence dimension_equations k k' ->
    (InvBack k c e w b r <-> InvBack k' c e w b r);
  pres_delta_respects_dimensions : forall k k' l l' c e w c' e' w',
    dim_congruence dimension_equations k k' ->
    dim_congruence dimension_equations l l' ->
    (PresDelta k l c e w c' e' w' <->
     PresDelta k' l' c e w c' e' w');
  pres_back_respects_dimensions :
    forall k k' l l' c e w b r c' e' w' b' r',
    dim_congruence dimension_equations k k' ->
    dim_congruence dimension_equations l l' ->
    (PresBack k l c e w b r c' e' w' b' r' <->
     PresBack k' l' c e w b r c' e' w' b' r');
  back_respects_dimension : forall k k' c e b r,
    dim_congruence dimension_equations k k' ->
    (Back k c e b r <-> Back k' c e b r)
}.

Definition Dimension (A : ComparisonCalculus) : Type :=
  DimTerm (AtomDim (dimension_basis A)).

Definition dimension_equiv (A : ComparisonCalculus)
    : Dimension A -> Dimension A -> Prop :=
  dim_congruence (dimension_equations A).

Arguments dimension_equiv A _ _ : clear implicits.

Definition dim_tensor (A : ComparisonCalculus)
    : Dimension A -> Dimension A -> Dimension A := DTensor.
Definition dim_option (A : ComparisonCalculus)
    : Dimension A -> Dimension A -> Dimension A := DOption.
Definition dim_sequence (A : ComparisonCalculus)
    : Dimension A -> Dimension A -> Dimension A := DSeq.

(** These five dimensions are not arbitrary record fields: they are the
    canonical quotient classes of the five distinguished atoms. *)
Definition dim_bind (A : ComparisonCalculus) : Dimension A :=
  Bind (dimension_basis A).
Definition dim_rule (A : ComparisonCalculus) : Dimension A :=
  RuleDim (dimension_basis A).
Definition dim_model (A : ComparisonCalculus) : Dimension A :=
  ModelDim (dimension_basis A).
Definition dim_truth (A : ComparisonCalculus) : Dimension A :=
  TruthDim (dimension_basis A).
Definition dim_boundary (A : ComparisonCalculus) : Dimension A :=
  BoundaryDim (dimension_basis A).

Arguments dim_tensor A _ _ : clear implicits.
Arguments dim_option A _ _ : clear implicits.
Arguments dim_sequence A _ _ : clear implicits.
Arguments dim_bind A : clear implicits.
Arguments dim_rule A : clear implicits.
Arguments dim_model A : clear implicits.
Arguments dim_truth A : clear implicits.
Arguments dim_boundary A : clear implicits.

Definition correct_path (B : BottomEnvironment) (p : list (Correct B)) : Prop :=
  adjacent (correct_step B) p.

Definition ordinary_error_path
    (B : BottomEnvironment) (p : list (Error B)) : Prop :=
  adjacent (ordinary_error_step B) p.

Definition diff_set (A : ComparisonCalculus)
    (k : Dimension A) (c : Correct (base A)) (e : Error (base A))
    : Witness A -> Prop :=
  fun w => Diff A k c e w.

Definition next_set (A : ComparisonCalculus)
    (k : Dimension A) (c : Correct (base A)) (e : Error (base A))
    : Correct (base A) * Error (base A) -> Prop :=
  fun ce => Next A k c e (fst ce) (snd ce).

Definition back_set (A : ComparisonCalculus)
    (k : Dimension A) (c : Correct (base A)) (e : Error (base A))
    : Boundary (base A) * Rule (base A) -> Prop :=
  fun br => Back A k c e (fst br) (snd br).

(** Sections 4--5: object-language judgments and comparison-node terms. *)

Inductive ObjAtom (A : ComparisonCalculus) : Type :=
| DiffAt : Dimension A -> Correct (base A) -> Error (base A) ->
           Witness A -> ObjAtom A
| CmpAt : Dimension A -> Correct (base A) -> Error (base A) -> ObjAtom A.

Arguments DiffAt {A} _ _ _ _.
Arguments CmpAt {A} _ _ _.

Inductive obj_derives (A : ComparisonCalculus) : ObjAtom A -> Prop :=
| ObjCmpIntro : forall k c e w,
    Diff A k c e w ->
    @obj_derives A (CmpAt k c e).

Theorem obj_cmp_iff_has_diff :
  forall (A : ComparisonCalculus) k c e,
    @obj_derives A (CmpAt k c e) <->
    exists w, Diff A k c e w.
Proof.
  intros A k c e.
  split.
  - intros H.
    inversion H as [k' c' e' w Hdiff].
    exists w.
    exact Hdiff.
  - intros [w Hdiff].
    econstructor.
    exact Hdiff.
Qed.

Record CNode (A : ComparisonCalculus) : Type := mkCNode {
  node_correct : Correct (base A);
  node_error : Error (base A);
  node_dimension : Dimension A;
  node_witness : Witness A
}.

Arguments mkCNode {A} _ _ _ _.

Definition cnode_valid (A : ComparisonCalculus) (x : CNode A) : Prop :=
  Diff A (node_dimension x) (node_correct x) (node_error x)
         (node_witness x) /\
  InvDelta A (node_dimension x) (node_correct x) (node_error x)
             (node_witness x).

Lemma valid_node_yields_object_comparison :
  forall (A : ComparisonCalculus) (x : CNode A),
    @cnode_valid A x ->
    @obj_derives A
      (CmpAt (node_dimension x) (node_correct x) (node_error x)).
Proof.
  intros A x [Hdiff _].
  econstructor.
    exact Hdiff.
Qed.


(** Sections 6--7: partial path selectors and legal comparison paths. *)

Record PathSelector (A : ComparisonCalculus) : Type := {
  select_path : list (Error (base A)) -> option (list (Correct (base A)));
  select_only_nonempty : forall s cs,
      select_path s = Some cs -> s <> [];
  select_length : forall s cs,
      select_path s = Some cs -> length cs = length s;
  select_correct : forall s cs,
      select_path s = Some cs -> correct_path (base A) cs;
  select_prefix_closed : forall s cs m,
      select_path s = Some cs ->
      1 <= m <= length s ->
      exists cs', select_path (firstn m s) = Some cs';
  select_prefix_compatible : forall s t cs ct,
      select_path s = Some cs ->
      select_path t = Some ct ->
      s = firstn (length s) t ->
      cs = firstn (length s) ct
}.

Definition ErrSeq {A : ComparisonCalculus} (P : list (CNode A))
    : list (Error (base A)) :=
  map (@node_error A) P.

Definition CorrSeq {A : ComparisonCalculus} (P : list (CNode A))
    : list (Correct (base A)) :=
  map (@node_correct A) P.

Definition DimSeq {A : ComparisonCalculus} (P : list (CNode A))
    : list (Dimension A) :=
  map (@node_dimension A) P.

(** Equality of dimension sequences is equality in the presented quotient,
    pointwise, rather than Rocq's syntactic equality of representatives. *)
Definition quotient_dimseq_equiv {A : ComparisonCalculus}
    (P Q : list (CNode A)) : Prop :=
  Forall2 (dimension_equiv A) (DimSeq P) (DimSeq Q).

Definition WitSeq {A : ComparisonCalculus} (P : list (CNode A))
    : list (Witness A) :=
  map (@node_witness A) P.

Definition node_next {A : ComparisonCalculus} (x y : CNode A) : Prop :=
  Next A (node_dimension x) (node_correct x) (node_error x)
         (node_correct y) (node_error y).

Definition node_pres_delta {A : ComparisonCalculus}
    (x y : CNode A) : Prop :=
  PresDelta A (node_dimension x) (node_dimension y)
    (node_correct x) (node_error x) (node_witness x)
    (node_correct y) (node_error y) (node_witness y).

Definition legal_path {A : ComparisonCalculus}
    (sigma : PathSelector A) (P : list (CNode A)) : Prop :=
  P <> [] /\
  select_path sigma (ErrSeq P) = Some (CorrSeq P) /\
  Forall (@cnode_valid A) P /\
  adjacent node_next P /\
  adjacent node_pres_delta P.

Definition LPath {A : ComparisonCalculus}
    (sigma : PathSelector A) (n : nat) : list (CNode A) -> Prop :=
  fun P => length P = n /\ legal_path sigma P.

Lemma legal_path_selected_correct :
  forall (A : ComparisonCalculus) (sigma : PathSelector A) P,
    legal_path sigma P ->
    correct_path (base A) (CorrSeq P).
Proof.
  intros A sigma P [_ [Hselect _]].
  exact (select_correct sigma (ErrSeq P) Hselect).
Qed.

Lemma legal_path_selected_length :
  forall (A : ComparisonCalculus) (sigma : PathSelector A) P,
    legal_path sigma P ->
    length (CorrSeq P) = length (ErrSeq P).
Proof.
  intros A sigma P [_ [Hselect _]].
  exact (select_length sigma (ErrSeq P) Hselect).
Qed.

(** Section 8: continuation, failed attempts, and the terminal noise layer. *)

Fixpoint last_opt {A : Type} (xs : list A) : option A :=
  match xs with
  | [] => None
  | x :: [] => Some x
  | _ :: xs' => last_opt xs'
  end.

Definition can_continue {A : ComparisonCalculus}
    (sigma : PathSelector A) (P : list (CNode A))
    (cstar : Correct (base A)) (estar : Error (base A))
    (lambda : Dimension A) : Prop :=
  exists wstar,
    legal_path sigma (P ++ [mkCNode cstar estar lambda wstar]).

Definition fail_attempt {A : ComparisonCalculus}
    (sigma : PathSelector A) (P : list (CNode A))
    (cstar : Correct (base A)) (estar : Error (base A))
    (lambda : Dimension A) : Prop :=
  exists previous,
    last_opt P = Some previous /\
    Next A (node_dimension previous)
      (node_correct previous) (node_error previous) cstar estar /\
    select_path sigma (ErrSeq P ++ [estar]) =
      Some (CorrSeq P ++ [cstar]) /\
    ~ can_continue sigma P cstar estar lambda.

Definition extension_witness {A : ComparisonCalculus}
    (P : list (CNode A))
    (cstar : Correct (base A)) (estar : Error (base A))
    (lambda : Dimension A) (wstar : Witness A) : Prop :=
  exists previous,
    last_opt P = Some previous /\
    Diff A lambda cstar estar wstar /\
    InvDelta A lambda cstar estar wstar /\
    PresDelta A (node_dimension previous) lambda
      (node_correct previous) (node_error previous) (node_witness previous)
      cstar estar wstar.

(** [reason] is intentionally partial.  The source gives no value when a
    difference witness also satisfies the invariant and preservation test. *)
Definition reason {A : ComparisonCalculus}
    (sigma : PathSelector A) (P : list (CNode A))
    (cstar : Correct (base A)) (estar : Error (base A))
    (lambda : Dimension A) : option nat :=
  if excluded_middle_informative
       (exists wstar, Diff A lambda cstar estar wstar)
  then
    if excluded_middle_informative
         (exists wstar, extension_witness P cstar estar lambda wstar)
    then None
    else Some 1
  else Some 0.

Lemma reason_zero_iff_no_diff :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         P cstar estar lambda,
    reason sigma P cstar estar lambda = Some 0 <->
    forall w, ~ Diff A lambda cstar estar w.
Proof.
  intros A sigma P cstar estar lambda.
  unfold reason.
  destruct (excluded_middle_informative
    (exists wstar, Diff A lambda cstar estar wstar)) as [Hex | Hnone].
  - destruct (excluded_middle_informative
      (exists wstar, extension_witness P cstar estar lambda wstar)).
    + split.
      * discriminate.
      * intros Hall.
        destruct Hex as [w Hw].
        exact (False_rect _ (Hall w Hw)).
    + split.
      * discriminate.
      * intros Hall.
        destruct Hex as [w Hw].
        exact (False_rect _ (Hall w Hw)).
  - split.
    + intros _ w Hw.
      apply Hnone.
      exists w.
      exact Hw.
    + intros _.
      reflexivity.
Qed.

Lemma reason_one_iff_diff_but_no_valid_extension_witness :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         P cstar estar lambda,
    reason sigma P cstar estar lambda = Some 1 <->
    (exists w, Diff A lambda cstar estar w) /\
    ~ (exists w, extension_witness P cstar estar lambda w).
Proof.
  intros A sigma P cstar estar lambda.
  unfold reason.
  destruct (excluded_middle_informative
    (exists wstar, Diff A lambda cstar estar wstar)) as [Hex | Hnone].
  - destruct (excluded_middle_informative
      (exists wstar, extension_witness P cstar estar lambda wstar))
      as [Hext | Hnoext].
    + split.
      * discriminate.
      * intros [_ Hcontra].
        exact (False_rect _ (Hcontra Hext)).
    + split.
      * intros _.
        split; assumption.
      * intros _.
        reflexivity.
  - split.
    + discriminate.
    + intros [Hex _].
      exact (False_rect _ (Hnone Hex)).
Qed.

Lemma adjacent_snoc :
  forall (T : Type) (R : T -> T -> Prop)
         (xs : list T) last x,
    xs <> [] ->
    last_opt xs = Some last ->
    adjacent R xs ->
    R last x ->
    adjacent R (xs ++ [x]).
Proof.
  intros T R xs.
  induction xs as [| a xs IH].
  - intros last x Hnonempty.
    contradiction.
  - intros last x Hnonempty Hlast Hadj Hstep.
    destruct xs as [| b tail].
    + simpl in Hlast.
      inversion Hlast.
      subst last.
      simpl.
      split.
      * exact Hstep.
      * exact I.
    + change (last_opt (b :: tail) = Some last) in Hlast.
      change (R a b /\ adjacent R (b :: tail)) in Hadj.
      change (R a b /\ adjacent R ((b :: tail) ++ [x])).
      destruct Hadj as [Hab Htail].
      split.
      * exact Hab.
      * apply (IH last x).
        -- discriminate.
        -- exact Hlast.
        -- exact Htail.
        -- exact Hstep.
Qed.

Lemma extension_witness_yields_can_continue :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         P cstar estar lambda,
    legal_path sigma P ->
    fail_attempt sigma P cstar estar lambda ->
    (exists w, extension_witness P cstar estar lambda w) ->
    can_continue sigma P cstar estar lambda.
Proof.
  intros A sigma P cstar estar lambda Hlegal Hfail Hext.
  destruct Hlegal as [Hnonempty [Hselected [Hnodes [Hnext Hpres]]]].
  destruct Hfail as [previous
    [Hlast [Hnextstar [Hselectedstar Hcannot]]]].
  destruct Hext as [w [previous'
    [Hlast' [Hdiff [Hinv Hpresstar]]]]].
  assert (Hprevious : previous = previous') by congruence.
  subst previous'.
  unfold can_continue.
  exists w.
  split.
  - intros Hnil.
    apply app_eq_nil in Hnil.
    destruct Hnil as [HP _].
    exact (Hnonempty HP).
  - split.
    + unfold ErrSeq, CorrSeq in *.
      rewrite !map_app.
      simpl.
      exact Hselectedstar.
    + split.
      * apply Forall_app.
        split.
        -- exact Hnodes.
        -- constructor.
           ++ split; assumption.
           ++ constructor.
      * split.
        -- eapply adjacent_snoc.
           ++ exact Hnonempty.
           ++ exact Hlast.
           ++ exact Hnext.
           ++ exact Hnextstar.
        -- eapply adjacent_snoc.
           ++ exact Hnonempty.
           ++ exact Hlast.
           ++ exact Hpres.
           ++ exact Hpresstar.
Qed.

Theorem failed_attempt_reason_is_defined :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         P cstar estar lambda,
    legal_path sigma P ->
    fail_attempt sigma P cstar estar lambda ->
    exists q, reason sigma P cstar estar lambda = Some q.
Proof.
  intros A sigma P cstar estar lambda Hlegal Hfail.
  unfold reason.
  destruct (excluded_middle_informative
    (exists wstar, Diff A lambda cstar estar wstar)) as [Hex | Hnone].
  - destruct (excluded_middle_informative
      (exists wstar, extension_witness P cstar estar lambda wstar))
      as [Hext | Hnoext].
    + exfalso.
      destruct Hfail as [previous
        [Hlast [Hnextstar [Hselectedstar Hcannot]]]].
      apply Hcannot.
      eapply extension_witness_yields_can_continue.
      * exact Hlegal.
      * exists previous.
        repeat split; assumption.
      * exact Hext.
    + exists 1.
      reflexivity.
  - exists 0.
    reflexivity.
Qed.

(** The displayed source record has eight components including its Noise tag;
    the prose calling it a seven-tuple is corrected here. The constructor is
    the tag and the following seven fields are its payload. *)
Record NoiseRecord (A : ComparisonCalculus) : Type := mkNoiseRecord {
  noise_prefix : list (CNode A);
  noise_correct : Correct (base A);
  noise_error : Error (base A);
  noise_dimension : Dimension A;
  noise_error_sequence : list (Error (base A));
  noise_correct_sequence : list (Correct (base A));
  noise_reason : nat
}.

Arguments mkNoiseRecord {A} _ _ _ _ _ _ _.

Definition canonical_noise_record {A : ComparisonCalculus}
    (sigma : PathSelector A) (P : list (CNode A))
    (cstar : Correct (base A)) (estar : Error (base A))
    (lambda : Dimension A) : option (NoiseRecord A) :=
  match reason sigma P cstar estar lambda with
  | Some q =>
      Some (mkNoiseRecord P cstar estar lambda
        (ErrSeq P ++ [estar]) (CorrSeq P ++ [cstar]) q)
  | None => None
  end.

Definition valid_noise_record {A : ComparisonCalculus}
    (sigma : PathSelector A) (nu : NoiseRecord A) : Prop :=
  legal_path sigma (noise_prefix nu) /\
  fail_attempt sigma (noise_prefix nu)
    (noise_correct nu) (noise_error nu) (noise_dimension nu) /\
  noise_error_sequence nu = ErrSeq (noise_prefix nu) ++ [noise_error nu] /\
  noise_correct_sequence nu = CorrSeq (noise_prefix nu) ++ [noise_correct nu] /\
  reason sigma (noise_prefix nu)
    (noise_correct nu) (noise_error nu) (noise_dimension nu) =
    Some (noise_reason nu).
Inductive PathObject (A : ComparisonCalculus) : Type :=
| LegalObject : list (CNode A) -> PathObject A
| NoiseObject : NoiseRecord A -> PathObject A.

Arguments LegalObject {A} _.
Arguments NoiseObject {A} _.

Definition valid_object {A : ComparisonCalculus}
    (sigma : PathSelector A) (X : PathObject A) : Prop :=
  match X with
  | LegalObject P => legal_path sigma P
  | NoiseObject nu => valid_noise_record sigma nu
  end.

(** The source defines [FailErase_sigma] only on legal paths and valid noise
    paths.  Packaging the membership proof in the input prevents constructing
    a failure theory for an arbitrary, malformed path object. *)
Record CertifiedPathObject (A : ComparisonCalculus)
    (sigma : PathSelector A) : Type := {
  certified_object : PathObject A;
  certified_object_valid : valid_object sigma certified_object
}.

Arguments certified_object {A sigma} _.
Arguments certified_object_valid {A sigma} _.

Definition object_successor {A : ComparisonCalculus}
    (sigma : PathSelector A) (X Y : PathObject A) : Prop :=
  match X with
  | LegalObject P =>
      exists x, Y = LegalObject (P ++ [x]) /\ legal_path sigma (P ++ [x])
  | NoiseObject _ => False
  end.

Theorem noise_objects_are_terminal :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (nu : NoiseRecord A) Y,
    ~ object_successor sigma (NoiseObject nu) Y.
Proof.
  intros A sigma nu Y H.
  exact H.
Qed.

(** Section 9: filtered local backtracking and path-level backtracking. *)

Definition BackInterface (A : ComparisonCalculus) : Type :=
  (Boundary (base A) * Rule (base A))%type.

Definition local_back {A : ComparisonCalculus}
    (x : CNode A) (br : BackInterface A) : Prop :=
  Back A (node_dimension x) (node_correct x) (node_error x)
       (fst br) (snd br) /\
  InvBack A (node_dimension x) (node_correct x) (node_error x)
    (node_witness x) (fst br) (snd br).

Fixpoint all_local_back {A : ComparisonCalculus}
    (P : list (CNode A)) (rho : list (BackInterface A)) : Prop :=
  match P, rho with
  | [], [] => True
  | x :: P', br :: rho' => local_back x br /\ all_local_back P' rho'
  | _, _ => False
  end.

Definition back_pres_step {A : ComparisonCalculus}
    (x : CNode A) (br : BackInterface A)
    (y : CNode A) (br' : BackInterface A) : Prop :=
  PresBack A (node_dimension x) (node_dimension y)
    (node_correct x) (node_error x) (node_witness x) (fst br) (snd br)
    (node_correct y) (node_error y) (node_witness y) (fst br') (snd br').

Fixpoint back_preserved_from {A : ComparisonCalculus}
    (x : CNode A) (br : BackInterface A)
    (P : list (CNode A)) (rho : list (BackInterface A)) : Prop :=
  match P, rho with
  | [], [] => True
  | y :: P', br' :: rho' =>
      back_pres_step x br y br' /\ back_preserved_from y br' P' rho'
  | _, _ => False
  end.

Definition back_preserved {A : ComparisonCalculus}
    (P : list (CNode A)) (rho : list (BackInterface A)) : Prop :=
  match P, rho with
  | [], [] => True
  | x :: P', br :: rho' => back_preserved_from x br P' rho'
  | _, _ => False
  end.

Definition BackTrace {A : ComparisonCalculus}
    (P : list (CNode A)) (rho : list (BackInterface A)) : Prop :=
  length rho = length P /\
  all_local_back P rho /\
  back_preserved P rho.

Fixpoint fold_dimensions {A : ComparisonCalculus}
    (acc : Dimension A) (ks : list (Dimension A)) : Dimension A :=
  match ks with
  | [] => acc
  | k :: ks' => fold_dimensions (dim_sequence A acc k) ks'
  end.

Definition DimFold {A : ComparisonCalculus}
    (P : list (CNode A)) : option (Dimension A) :=
  match DimSeq P with
  | [] => None
  | k :: ks => Some (fold_dimensions k ks)
  end.

Definition PathBackElement (A : ComparisonCalculus) : Type :=
  (Dimension A * list (BackInterface A))%type.

Definition PathBack {A : ComparisonCalculus}
    (P : list (CNode A)) : PathBackElement A -> Prop :=
  fun z =>
    exists d rho,
      z = (d, rho) /\
      DimFold P = Some d /\
      BackTrace P rho.

Definition HistBack {A : ComparisonCalculus}
    (X : PathObject A) : PathBackElement A -> Prop :=
  match X with
  | LegalObject P => PathBack P
  | NoiseObject nu => PathBack (noise_prefix nu)
  end.

Definition CurrentBack {A : ComparisonCalculus}
    (X : PathObject A) : PathBackElement A -> Prop :=
  match X with
  | LegalObject P => PathBack P
  | NoiseObject _ => fun _ => False
  end.

Lemma noise_preserves_history_but_permits_no_backtracking :
  forall (A : ComparisonCalculus) (nu : NoiseRecord A),
    (forall z, HistBack (NoiseObject nu) z <-> PathBack (noise_prefix nu) z) /\
    (forall z, ~ CurrentBack (NoiseObject nu) z).
Proof.
  intros A nu.
  split.
  - intros z.
    split.
    + intros H.
      exact H.
    + intros H.
      exact H.
  - intros z H.
    exact H.
Qed.

(** Sections 10 and 15: raw erasure and ordinary observable equivalence. *)

Definition RawErase {A : ComparisonCalculus}
    (X : PathObject A) : list (Error (base A)) :=
  match X with
  | LegalObject P => ErrSeq P
  | NoiseObject nu => noise_error_sequence nu
  end.

Definition NoiseFlag {A : ComparisonCalculus} (X : PathObject A) : bool :=
  match X with
  | LegalObject _ => false
  | NoiseObject _ => true
  end.

Definition OrdObs {A : ComparisonCalculus} (X : PathObject A)
    : list (Error (base A)) * bool :=
  (RawErase X, NoiseFlag X).

Definition ordinary_failure_equiv {A : ComparisonCalculus}
    (X Y : PathObject A) : Prop :=
  OrdObs X = OrdObs Y.

(** Sections 11--12: first-order LP semantics and the fixed universal core. *)

Inductive PredicateSymbol : Type :=
| PU
| PCorrectNode
| PErrorNode
| PDimension
| PWitness
| PDiff
| PCmp
| PInvD
| PPresD
| PNextPair
| PBackInterface
| PPriorBackInterface
| PBackTrace
| PPriorBackTrace
| PNoiseRecord
| PAttemptedCmp
| PRawErrorAt
| PSelectedCorrectAt
| PReflectNode
| PReflectCmp
| PReflectStep
| PProofReflects
| PConflict.

Definition predicate_arity (p : PredicateSymbol) : nat :=
  match p with
  | PU => 4
  | PCorrectNode | PErrorNode | PDimension | PWitness | PConflict => 1
  | PDiff | PInvD => 4
  | PCmp => 3
  | PPresD => 8
  | PNextPair => 7
  | PBackInterface | PPriorBackInterface => 7
  | PBackTrace | PPriorBackTrace => 3
  | PNoiseRecord => 6
  | PAttemptedCmp => 5
  | PRawErrorAt | PSelectedCorrectAt => 3
  | PReflectNode => 6
  | PReflectCmp => 6
  | PReflectStep => 7
  | PProofReflects => 2
  end.

Inductive FOTerm (Const : Type) : Type :=
| TVar : nat -> FOTerm Const
| TConst : Const -> FOTerm Const
| TZero : FOTerm Const
| TSucc : FOTerm Const -> FOTerm Const
| TPlus : FOTerm Const -> FOTerm Const -> FOTerm Const
| TTimes : FOTerm Const -> FOTerm Const -> FOTerm Const.

Arguments TVar {Const} _.
Arguments TConst {Const} _.
Arguments TZero {Const}.
Arguments TSucc {Const} _.
Arguments TPlus {Const} _ _.
Arguments TTimes {Const} _ _.

Inductive Formula (Const : Type) : Type :=
| FAtom : PredicateSymbol -> list (FOTerm Const) -> Formula Const
| FNeg : Formula Const -> Formula Const
| FAnd : Formula Const -> Formula Const -> Formula Const
| FOr : Formula Const -> Formula Const -> Formula Const
| FForall : nat -> Formula Const -> Formula Const
| FExists : nat -> Formula Const -> Formula Const.

Arguments FAtom {Const} _ _.
Arguments FNeg {Const} _.
Arguments FAnd {Const} _ _.
Arguments FOr {Const} _ _.
Arguments FForall {Const} _ _.
Arguments FExists {Const} _ _.

Definition FImp {Const : Type} (phi psi : Formula Const) : Formula Const :=
  FOr (FNeg phi) psi.

Fixpoint wf_formula {Const : Type} (phi : Formula Const) : Prop :=
  match phi with
  | FAtom p ts => length ts = predicate_arity p
  | FNeg p => wf_formula p
  | FAnd p q | FOr p q => wf_formula p /\ wf_formula q
  | FForall _ p | FExists _ p => wf_formula p
  end.

Fixpoint numeral {Const : Type} (n : nat) : FOTerm Const :=
  match n with
  | 0 => TZero
  | S n' => TSucc (numeral n')
  end.

Record TruthStatus : Type := {
  true_part : Prop;
  false_part : Prop
}.

Record LPModel (Const : Type) : Type := {
  lp_carrier : Type;
  lp_inhabitant : lp_carrier;
  lp_const : Const -> lp_carrier;
  lp_zero : lp_carrier;
  lp_succ : lp_carrier -> lp_carrier;
  lp_plus : lp_carrier -> lp_carrier -> lp_carrier;
  lp_times : lp_carrier -> lp_carrier -> lp_carrier;
  lp_positive : PredicateSymbol -> list lp_carrier -> Prop;
  lp_negative : PredicateSymbol -> list lp_carrier -> Prop
}.

Definition assignment {Const : Type} (M : LPModel Const) : Type :=
  nat -> lp_carrier M.

Definition update {A : Type} (g : nat -> A) (x : nat) (a : A) : nat -> A :=
  fun y => if Nat.eq_dec y x then a else g y.

Fixpoint eval_term {Const : Type} (M : LPModel Const)
    (g : assignment M) (t : FOTerm Const) : lp_carrier M :=
  match t with
  | TVar x => g x
  | TConst c => lp_const M c
  | TZero => lp_zero M
  | TSucc u => lp_succ M (@eval_term Const M g u)
  | TPlus u v => lp_plus M (@eval_term Const M g u) (@eval_term Const M g v)
  | TTimes u v => lp_times M (@eval_term Const M g u) (@eval_term Const M g v)
  end.

Definition eval_terms {Const : Type} (M : LPModel Const)
    (g : assignment M) (ts : list (FOTerm Const)) : list (lp_carrier M) :=
  map (@eval_term Const M g) ts.

Fixpoint lp_eval {Const : Type} (M : LPModel Const)
    (g : assignment M) (phi : Formula Const) : TruthStatus :=
  match phi with
  | FAtom p ts =>
      {| true_part := lp_positive M p (@eval_terms Const M g ts);
         false_part := lp_negative M p (@eval_terms Const M g ts) |}
  | FNeg p =>
      {| true_part := false_part (@lp_eval Const M g p);
         false_part := true_part (@lp_eval Const M g p) |}
  | FAnd p q =>
      {| true_part := true_part (@lp_eval Const M g p) /\
                       true_part (@lp_eval Const M g q);
         false_part := false_part (@lp_eval Const M g p) \/
                        false_part (@lp_eval Const M g q) |}
  | FOr p q =>
      {| true_part := true_part (@lp_eval Const M g p) \/
                       true_part (@lp_eval Const M g q);
         false_part := false_part (@lp_eval Const M g p) /\
                        false_part (@lp_eval Const M g q) |}
  | FForall x p =>
      {| true_part := forall a, true_part (@lp_eval Const M (update g x a) p);
         false_part := exists a, false_part (@lp_eval Const M (update g x a) p) |}
  | FExists x p =>
      {| true_part := exists a, true_part (@lp_eval Const M (update g x a) p);
         false_part := forall a, false_part (@lp_eval Const M (update g x a) p) |}
  end.

Definition designated {Const : Type} (M : LPModel Const)
    (g : assignment M) (phi : Formula Const) : Prop :=
  true_part (@lp_eval Const M g phi).

Definition Theory (Const : Type) : Type := Formula Const -> Prop.

Definition lp_entails {Const : Type}
    (Gamma : Theory Const) (phi : Formula Const) : Prop :=
  forall (M : LPModel Const) (g : assignment M),
    (forall gamma, Gamma gamma -> @designated Const M g gamma) ->
    @designated Const M g phi.

Inductive TestConst : Type := TestX.

Definition lp_test_chi : Formula TestConst :=
  FAtom PConflict [TConst TestX].
Definition lp_test_psi : Formula TestConst :=
  FAtom PCorrectNode [TConst TestX].
Definition lp_test_premises : Theory TestConst :=
  fun phi => phi = lp_test_chi \/ phi = FNeg lp_test_chi.

Definition lp_test_positive (p : PredicateSymbol) (_ : list unit) : Prop :=
  match p with
  | PConflict => True
  | _ => False
  end.

Definition lp_test_negative (p : PredicateSymbol) (_ : list unit) : Prop :=
  match p with
  | PConflict => True
  | _ => False
  end.

Definition lp_test_model : LPModel TestConst := {|
  lp_carrier := unit;
  lp_inhabitant := tt;
  lp_const := fun _ => tt;
  lp_zero := tt;
  lp_succ := fun _ => tt;
  lp_plus := fun _ _ => tt;
  lp_times := fun _ _ => tt;
  lp_positive := lp_test_positive;
  lp_negative := lp_test_negative
|}.

Theorem lp_is_nonexplosive :
  ~ lp_entails lp_test_premises lp_test_psi.
Proof.
  intros Hexplode.
  specialize (Hexplode lp_test_model (fun _ => tt)).
  assert (Hall :
    forall gamma, lp_test_premises gamma ->
      @designated TestConst lp_test_model (fun _ => tt) gamma).
  - intros gamma [Hgamma | Hgamma].
    + subst gamma.
      exact I.
    + subst gamma.
      exact I.
  - specialize (Hexplode Hall).
    exact Hexplode.
Qed.


Lemma eval_numeral_assignment_irrelevant :
  forall (Const : Type) (M : LPModel Const)
         (g h : assignment M) n,
    @eval_term Const M g (numeral n) =
    @eval_term Const M h (numeral n).
Proof.
  intros Const M g h n.
  induction n as [| n IH].
  - reflexivity.
  - simpl.
    rewrite IH.
    reflexivity.
Qed.
Definition PartialFunction (f : nat -> nat -> Prop) : Prop :=
  forall x y z, f x y -> f x z -> y = z.

Record UniversalMachine : Type := {
  UTM : nat -> nat -> nat -> nat -> Prop;
  PartialRecursive : (nat -> nat -> Prop) -> Prop;
  partial_recursive_is_function : forall f,
      PartialRecursive f -> PartialFunction f;
  universal_program : forall f,
      PartialRecursive f ->
      exists p, forall x y,
        f x y <-> exists t, UTM p x t y
}.

Definition u_atom {Const : Type} (p x t y : nat) : Formula Const :=
  FAtom PU [numeral p; numeral x; numeral t; numeral y].

Definition TC {Const : Type} (U : UniversalMachine) : Theory Const :=
  fun phi =>
    exists p x t y,
      UTM U p x t y /\
      phi = u_atom p x t y.

Definition halts_formula {Const : Type} (p x y : nat) : Formula Const :=
  FExists 0
    (FAtom PU [numeral p; numeral x; TVar 0; numeral y]).


Lemma halts_witness_designated :
  forall (Const : Type) (M : LPModel Const)
         (g : assignment M) p x t y,
    @designated Const M g (@u_atom Const p x t y) ->
    @designated Const M
      (update g 0 (@eval_term Const M g (numeral t)))
      (FAtom PU [numeral p; numeral x; TVar 0; numeral y]).
Proof.
  intros Const M g p x t y H.
  change (lp_positive M PU
    [@eval_term Const M g (numeral p);
     @eval_term Const M g (numeral x);
     @eval_term Const M g (numeral t);
     @eval_term Const M g (numeral y)]) in H.
  change (lp_positive M PU
    [@eval_term Const M
       (update g 0 (@eval_term Const M g (numeral t))) (numeral p);
     @eval_term Const M
       (update g 0 (@eval_term Const M g (numeral t))) (numeral x);
     @eval_term Const M g (numeral t);
     @eval_term Const M
       (update g 0 (@eval_term Const M g (numeral t))) (numeral y)]).
  rewrite (@eval_numeral_assignment_irrelevant
    Const M (update g 0 (@eval_term Const M g (numeral t))) g p).
  rewrite (@eval_numeral_assignment_irrelevant
    Const M (update g 0 (@eval_term Const M g (numeral t))) g x).
  rewrite (@eval_numeral_assignment_irrelevant
    Const M (update g 0 (@eval_term Const M g (numeral t))) g y).
  exact H.
Qed.
Theorem tc_entails_halts :
  forall (Const : Type) (U : UniversalMachine) p x t y,
    UTM U p x t y ->
    lp_entails (@TC Const U) (halts_formula p x y).
Proof.
  intros Const U p x t y Hstep M g Hall.
  specialize (Hall (@u_atom Const p x t y)).
  assert (Hin : @TC Const U (@u_atom Const p x t y)).
  - exists p, x, t, y.
    split.
    + exact Hstep.
    + reflexivity.
  - specialize (Hall Hin).
    simpl.
    exists (@eval_term Const M g (numeral t)).
    apply (@halts_witness_designated Const M g p x t y).
    exact Hall.
Qed.

Theorem tc_expresses_every_partial_recursive_computation :
  forall (Const : Type) (U : UniversalMachine)
         (f : nat -> nat -> Prop),
    PartialRecursive U f ->
    exists p, forall x y,
      f x y ->
      lp_entails (@TC Const U) (halts_formula p x y).
Proof.
  intros Const U f Hrec.
  destruct (universal_program U f Hrec) as [p Hp].
  exists p.
  intros x y Hf.
  apply (proj1 (Hp x y)) in Hf.
  destruct Hf as [t Hstep].
  exact (@tc_entails_halts Const U p x t y Hstep).
Qed.

(** Sections 13--14: the path-indexed failure language and theory. *)

Inductive FailureConst (A : ComparisonCalculus) : Type :=
| FCPath : PathObject A -> FailureConst A
| FCNodeCorrect : nat -> Correct (base A) -> FailureConst A
| FCNodeError : nat -> Error (base A) -> FailureConst A
| FCNodeDimension : nat -> Dimension A -> FailureConst A
| FCNodeWitness : nat -> Witness A -> FailureConst A
| FCFoldDimension : Dimension A -> FailureConst A
| FCBackTrace : list (BackInterface A) -> FailureConst A
| FCBackBoundary : Boundary (base A) -> FailureConst A
| FCBackRule : Rule (base A) -> FailureConst A
| FCStarCorrect : Correct (base A) -> FailureConst A
| FCStarError : Error (base A) -> FailureConst A
| FCStarDimension : Dimension A -> FailureConst A
| FCNoiseReason : nat -> FailureConst A.

Arguments FCPath {A} _.
Arguments FCNodeCorrect {A} _ _.
Arguments FCNodeError {A} _ _.
Arguments FCNodeDimension {A} _ _.
Arguments FCNodeWitness {A} _ _.
Arguments FCFoldDimension {A} _.
Arguments FCBackTrace {A} _.
Arguments FCBackBoundary {A} _.
Arguments FCBackRule {A} _.
Arguments FCStarCorrect {A} _.
Arguments FCStarError {A} _.
Arguments FCStarDimension {A} _.
Arguments FCNoiseReason {A} _.

Definition object_prefix {A : ComparisonCalculus}
    (X : PathObject A) : list (CNode A) :=
  match X with
  | LegalObject P => P
  | NoiseObject nu => noise_prefix nu
  end.

Lemma forall_nth_error :
  forall (T : Type) (P : T -> Prop) xs i x,
    Forall P xs ->
    nth_error xs i = Some x ->
    P x.
Proof.
  intros T P xs i x Hall Hnth.
  rewrite Forall_forall in Hall.
  apply Hall.
  eapply nth_error_In.
  exact Hnth.
Qed.

Lemma adjacent_nth_error :
  forall (T : Type) (R : T -> T -> Prop) xs i x y,
    adjacent R xs ->
    nth_error xs i = Some x ->
    nth_error xs (S i) = Some y ->
    R x y.
Proof.
  intros T R xs.
  induction xs as [| a xs IH].
  - intros i x y Hadj Hx.
    destruct i; discriminate.
  - intros i x y Hadj Hx Hy.
    destruct xs as [| b tail].
    + destruct i; discriminate.
    + destruct Hadj as [Hab Htail].
      destruct i as [| i].
      * simpl in Hx, Hy.
        inversion Hx; inversion Hy; subst.
        exact Hab.
      * simpl in Hx, Hy.
        eapply IH.
        -- exact Htail.
        -- exact Hx.
        -- exact Hy.
Qed.

Lemma valid_object_prefix_is_legal :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (X : PathObject A),
    valid_object sigma X ->
    legal_path sigma (object_prefix X).
Proof.
  intros A sigma X Hvalid.
  destruct X as [P | nu].
  - exact Hvalid.
  - exact (proj1 Hvalid).
Qed.

(** This certificate is the mechanism carried by the reflected formulas:
    every recorded node comes from an actual Diff/InvDelta comparison, and
    every recorded adjacent pair comes from actual Next/PresDelta data. *)
Record ReflectionProvenance {A : ComparisonCalculus}
    (sigma : PathSelector A) (X : PathObject A) : Prop := {
  reflected_node_diff : forall i node,
    nth_error (object_prefix X) i = Some node ->
    Diff A (node_dimension node) (node_correct node) (node_error node)
      (node_witness node);
  reflected_node_invariant : forall i node,
    nth_error (object_prefix X) i = Some node ->
    InvDelta A (node_dimension node) (node_correct node) (node_error node)
      (node_witness node);
  reflected_node_comparison : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @obj_derives A
      (CmpAt (node_dimension node) (node_correct node) (node_error node));
  reflected_step_next : forall i node next_node,
    nth_error (object_prefix X) i = Some node ->
    nth_error (object_prefix X) (S i) = Some next_node ->
    node_next node next_node;
  reflected_step_pres_delta : forall i node next_node,
    nth_error (object_prefix X) i = Some node ->
    nth_error (object_prefix X) (S i) = Some next_node ->
    node_pres_delta node next_node
}.

Theorem valid_object_has_reflection_provenance :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (X : PathObject A),
    valid_object sigma X ->
    ReflectionProvenance sigma X.
Proof.
  intros A sigma X Hvalid.
  pose proof (@valid_object_prefix_is_legal A sigma X Hvalid) as Hlegal.
  destruct Hlegal as [_ [_ [Hnodes [Hnext Hpres]]]].
  constructor.
  - intros i node Hnth.
    destruct (@forall_nth_error (CNode A) (@cnode_valid A)
      (object_prefix X) i node Hnodes Hnth) as [Hdiff Hinv].
    exact Hdiff.
  - intros i node Hnth.
    destruct (@forall_nth_error (CNode A) (@cnode_valid A)
      (object_prefix X) i node Hnodes Hnth) as [Hdiff Hinv].
    exact Hinv.
  - intros i node Hnth.
    apply valid_node_yields_object_comparison.
    exact (@forall_nth_error (CNode A) (@cnode_valid A)
      (object_prefix X) i node Hnodes Hnth).
  - intros i node next_node Hnth Hnextnth.
    eapply adjacent_nth_error; eauto.
  - intros i node next_node Hnth Hnextnth.
    eapply adjacent_nth_error; eauto.
Qed.

Inductive InFailureLanguage {A : ComparisonCalculus}
    (X : PathObject A) : FailureConst A -> Prop :=
| LangPath : InFailureLanguage X (FCPath X)
| LangNodeCorrect : forall i node,
    nth_error (object_prefix X) i = Some node ->
    InFailureLanguage X (FCNodeCorrect i (node_correct node))
| LangNodeError : forall i node,
    nth_error (object_prefix X) i = Some node ->
    InFailureLanguage X (FCNodeError i (node_error node))
| LangNodeDimension : forall i node,
    nth_error (object_prefix X) i = Some node ->
    InFailureLanguage X (FCNodeDimension i (node_dimension node))
| LangNodeWitness : forall i node,
    nth_error (object_prefix X) i = Some node ->
    InFailureLanguage X (FCNodeWitness i (node_witness node))
| LangFoldDimension : forall d rho,
    (HistBack X (d, rho) \/ CurrentBack X (d, rho)) ->
    InFailureLanguage X (FCFoldDimension d)
| LangTrace : forall d rho,
    (HistBack X (d, rho) \/ CurrentBack X (d, rho)) ->
    InFailureLanguage X (FCBackTrace rho)
| LangBackBoundary : forall d rho i br,
    (HistBack X (d, rho) \/ CurrentBack X (d, rho)) ->
    nth_error rho i = Some br ->
    InFailureLanguage X (FCBackBoundary (fst br))
| LangBackRule : forall d rho i br,
    (HistBack X (d, rho) \/ CurrentBack X (d, rho)) ->
    nth_error rho i = Some br ->
    InFailureLanguage X (FCBackRule (snd br))
| LangStarCorrect : forall nu,
    X = NoiseObject nu ->
    InFailureLanguage X (FCStarCorrect (noise_correct nu))
| LangStarError : forall nu,
    X = NoiseObject nu ->
    InFailureLanguage X (FCStarError (noise_error nu))
| LangStarDimension : forall nu,
    X = NoiseObject nu ->
    InFailureLanguage X (FCStarDimension (noise_dimension nu))
| LangNoiseReason : forall nu,
    X = NoiseObject nu ->
    InFailureLanguage X (FCNoiseReason (noise_reason nu)).

(** The object-indexed language as an actual subtype carrier.  The predicate
    [InFailureLanguage] is its characteristic membership relation. *)
Definition DynamicFailureLanguage {A : ComparisonCalculus}
    (X : PathObject A) : Type :=
  { c : FailureConst A | InFailureLanguage X c }.

Fixpoint term_in_failure_language {A : ComparisonCalculus}
    (X : PathObject A) (t : FOTerm (FailureConst A)) : Prop :=
  match t with
  | TVar _ | TZero => True
  | TConst c => InFailureLanguage X c
  | TSucc u => term_in_failure_language X u
  | TPlus u v | TTimes u v =>
      term_in_failure_language X u /\ term_in_failure_language X v
  end.

Fixpoint formula_in_failure_language {A : ComparisonCalculus}
    (X : PathObject A) (phi : Formula (FailureConst A)) : Prop :=
  match phi with
  | FAtom _ ts => Forall (term_in_failure_language X) ts
  | FNeg p => formula_in_failure_language X p
  | FAnd p q | FOr p q =>
      formula_in_failure_language X p /\ formula_in_failure_language X q
  | FForall _ p | FExists _ p => formula_in_failure_language X p
  end.

Definition tx {A : ComparisonCalculus} (X : PathObject A)
    : FOTerm (FailureConst A) := TConst (FCPath X).
Definition tcorr {A : ComparisonCalculus} (i : nat) (x : CNode A)
    : FOTerm (FailureConst A) := TConst (FCNodeCorrect i (node_correct x)).
Definition terr {A : ComparisonCalculus} (i : nat) (x : CNode A)
    : FOTerm (FailureConst A) := TConst (FCNodeError i (node_error x)).
Definition tdim {A : ComparisonCalculus} (i : nat) (x : CNode A)
    : FOTerm (FailureConst A) :=
  TConst (FCNodeDimension i (node_dimension x)).
Definition twit {A : ComparisonCalculus} (i : nat) (x : CNode A)
    : FOTerm (FailureConst A) :=
  TConst (FCNodeWitness i (node_witness x)).

Definition conflict_formula {A : ComparisonCalculus} (X : PathObject A)
    : Formula (FailureConst A) :=
  FAtom PConflict [tx X].

Inductive FailureTheory (A : ComparisonCalculus) (U : UniversalMachine)
    (X : PathObject A) : Theory (FailureConst A) :=
| I_TC : forall phi,
    @TC (FailureConst A) U phi ->
    @FailureTheory A U X phi
| I_Conflict :
    @FailureTheory A U X (conflict_formula X)
| I_NotConflict :
    @FailureTheory A U X (FNeg (conflict_formula X))
| I_CorrectNode : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PCorrectNode [tcorr i node])
| I_ErrorNode : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PErrorNode [terr i node])
| I_Dimension : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PDimension [tdim i node])
| I_Witness : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PWitness [twit i node])
| I_Diff : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PDiff [tdim i node; tcorr i node; terr i node; twit i node])
| I_Cmp : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PCmp [tdim i node; tcorr i node; terr i node])
| I_InvD : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PInvD [tdim i node; tcorr i node; terr i node; twit i node])
| I_ReflectNode : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PReflectNode
        [tx X; numeral i; tcorr i node; terr i node; tdim i node; twit i node])
| I_ReflectCmp : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PReflectCmp
        [tx X; numeral i; tdim i node; tcorr i node; terr i node; twit i node])
| I_ProofReflects : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PProofReflects [tx X; numeral i])
| I_NextPair : forall i node next_node,
    nth_error (object_prefix X) i = Some node ->
    nth_error (object_prefix X) (S i) = Some next_node ->
    @FailureTheory A U X
      (FAtom PNextPair
        [tx X; numeral i; tdim i node; tcorr i node; terr i node;
         tcorr (S i) next_node; terr (S i) next_node])
| I_PresD : forall i node next_node,
    nth_error (object_prefix X) i = Some node ->
    nth_error (object_prefix X) (S i) = Some next_node ->
    @FailureTheory A U X
      (FAtom PPresD
        [tdim i node; tdim (S i) next_node;
         tcorr i node; terr i node; twit i node;
         tcorr (S i) next_node; terr (S i) next_node;
         twit (S i) next_node])
| I_ReflectStep : forall i node next_node,
    nth_error (object_prefix X) i = Some node ->
    nth_error (object_prefix X) (S i) = Some next_node ->
    @FailureTheory A U X
      (FAtom PReflectStep
        [tx X; numeral i; tdim i node; tcorr i node; terr i node;
         tcorr (S i) next_node; terr (S i) next_node])
| I_RawErrorAt : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PRawErrorAt [tx X; numeral i; terr i node])
| I_SelectedCorrectAt : forall i node,
    nth_error (object_prefix X) i = Some node ->
    @FailureTheory A U X
      (FAtom PSelectedCorrectAt [tx X; numeral i; tcorr i node])
| I_BackTrace : forall P d rho,
    X = LegalObject P ->
    PathBack P (d, rho) ->
    @FailureTheory A U X
      (FAtom PBackTrace
        [tx X; TConst (FCBackTrace rho); TConst (FCFoldDimension d)])
| I_BackInterface : forall P d rho i node br,
    X = LegalObject P ->
    PathBack P (d, rho) ->
    nth_error P i = Some node ->
    nth_error rho i = Some br ->
    @FailureTheory A U X
      (FAtom PBackInterface
        [tx X; numeral i; tdim i node; tcorr i node; terr i node;
         TConst (FCBackBoundary (fst br));
         TConst (FCBackRule (snd br))])
| I_PriorBackTrace : forall nu d rho,
    X = NoiseObject nu ->
    PathBack (noise_prefix nu) (d, rho) ->
    @FailureTheory A U X
      (FAtom PPriorBackTrace
        [tx X; TConst (FCBackTrace rho); TConst (FCFoldDimension d)])
| I_PriorBackInterface : forall nu d rho i node br,
    X = NoiseObject nu ->
    PathBack (noise_prefix nu) (d, rho) ->
    nth_error (noise_prefix nu) i = Some node ->
    nth_error rho i = Some br ->
    @FailureTheory A U X
      (FAtom PPriorBackInterface
        [tx X; numeral i; tdim i node; tcorr i node; terr i node;
         TConst (FCBackBoundary (fst br));
         TConst (FCBackRule (snd br))])
| I_NoiseRecord : forall nu,
    X = NoiseObject nu ->
    @FailureTheory A U X
      (FAtom PNoiseRecord
        [tx X; numeral (length (noise_prefix nu));
         TConst (FCStarDimension (noise_dimension nu));
         TConst (FCStarCorrect (noise_correct nu));
         TConst (FCStarError (noise_error nu));
         TConst (FCNoiseReason (noise_reason nu))])
| I_AttemptedCmp : forall nu,
    X = NoiseObject nu ->
    @FailureTheory A U X
      (FAtom PAttemptedCmp
        [tx X; numeral (length (noise_prefix nu));
         TConst (FCStarDimension (noise_dimension nu));
         TConst (FCStarCorrect (noise_correct nu));
         TConst (FCStarError (noise_error nu))])
| I_NoiseRawError : forall nu,
    X = NoiseObject nu ->
    @FailureTheory A U X
      (FAtom PRawErrorAt
        [tx X; numeral (length (noise_prefix nu));
         TConst (FCStarError (noise_error nu))])
| I_NoiseSelectedCorrect : forall nu,
    X = NoiseObject nu ->
    @FailureTheory A U X
      (FAtom PSelectedCorrectAt
        [tx X; numeral (length (noise_prefix nu));
         TConst (FCStarCorrect (noise_correct nu))])
| I_NoDiffReason : forall nu,
    X = NoiseObject nu ->
    noise_reason nu = 0 ->
    @FailureTheory A U X
      (FForall 0
        (FNeg (FAtom PDiff
          [TConst (FCStarDimension (noise_dimension nu));
           TConst (FCStarCorrect (noise_correct nu));
           TConst (FCStarError (noise_error nu));
           TVar 0])))
| I_ReasonOne : forall nu,
    X = NoiseObject nu ->
    noise_reason nu = 1 ->
    @FailureTheory A U X
      (FAtom PNoiseRecord
        [tx X; numeral (length (noise_prefix nu));
         TConst (FCStarDimension (noise_dimension nu));
         TConst (FCStarCorrect (noise_correct nu));
         TConst (FCStarError (noise_error nu));
         numeral 1]).

Definition LPTag : Type := unit.

Lemma numerals_are_internal_to_dynamic_language :
  forall (A : ComparisonCalculus) (X : PathObject A) n,
    term_in_failure_language X (@numeral (FailureConst A) n).
Proof.
  intros A X n.
  induction n as [| n IH].
  - exact I.
  - simpl.
    exact IH.
Qed.

Theorem failure_theory_is_internal_to_dynamic_language :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A) phi,
    @FailureTheory A U X phi ->
    formula_in_failure_language X phi.
Proof.
  intros A U X phi Hphi.
  destruct Hphi; subst; simpl;
    repeat constructor;
    eauto using InFailureLanguage, numerals_are_internal_to_dynamic_language.
  all: try (destruct H as [p [x [t [y [_ Heq]]]]]; subst phi; simpl;
    repeat constructor; apply numerals_are_internal_to_dynamic_language).
  all: try (econstructor; [left; eassumption | eassumption]).
  all: try (econstructor; left; eassumption).
Qed.

Record FailEraseCode (A : ComparisonCalculus)
    (X : PathObject A) : Type := {
  fe_logic : LPTag;
  fe_language : FailureConst A -> Prop;
  fe_theory : Theory (FailureConst A);
  fe_theory_internal : forall phi,
    fe_theory phi -> formula_in_failure_language X phi;
  fe_consequence :
    Theory (FailureConst A) -> Formula (FailureConst A) -> Prop
}.

Definition FailErase (A : ComparisonCalculus) (sigma : PathSelector A)
    (U : UniversalMachine) (CX : @CertifiedPathObject A sigma)
    : @FailEraseCode A (certified_object CX) := {|
  fe_logic := tt;
  fe_language := InFailureLanguage (certified_object CX);
  fe_theory := @FailureTheory A U (certified_object CX);
  fe_theory_internal :=
    @failure_theory_is_internal_to_dynamic_language
      A U (certified_object CX);
  fe_consequence := @lp_entails (FailureConst A)
|}.

Theorem failerase_source_has_reflection_provenance :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (U : UniversalMachine) (CX : @CertifiedPathObject A sigma),
    ReflectionProvenance sigma (certified_object CX).
Proof.
  intros A sigma U CX.
  apply valid_object_has_reflection_provenance.
  exact (certified_object_valid CX).
Qed.

Theorem failure_theory_contains_TC :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A) phi,
    @TC (FailureConst A) U phi ->
    @FailureTheory A U X phi.
Proof.
  intros A U X phi Htc.
  exact (@I_TC A U X phi Htc).
Qed.

Theorem failure_theory_has_explicit_classical_conflict :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A),
    @FailureTheory A U X (conflict_formula X) /\
    @FailureTheory A U X (FNeg (conflict_formula X)).
Proof.
  intros A U X.
  split.
  - exact (@I_Conflict A U X).
  - exact (@I_NotConflict A U X).
Qed.

Definition failure_positive {A : ComparisonCalculus} (X : PathObject A)
    (p : PredicateSymbol) (args : list (FOTerm (FailureConst A))) : Prop :=
  match p, args with
  | PCorrectNode, [TConst (FCPath _)] => False
  | _, _ => True
  end.

Definition failure_negative {A : ComparisonCalculus} (_ : PathObject A)
    (_ : PredicateSymbol) (_ : list (FOTerm (FailureConst A))) : Prop := True.

Definition failure_countermodel {A : ComparisonCalculus} (X : PathObject A)
    : LPModel (FailureConst A) := {|
  lp_carrier := FOTerm (FailureConst A);
  lp_inhabitant := TZero;
  lp_const := TConst;
  lp_zero := TZero;
  lp_succ := TSucc;
  lp_plus := TPlus;
  lp_times := TTimes;
  lp_positive := failure_positive X;
  lp_negative := failure_negative X
|}.

Definition unrelated_formula {A : ComparisonCalculus} (X : PathObject A)
    : Formula (FailureConst A) :=
  FAtom PCorrectNode [TConst (FCPath X)].

Lemma every_failure_axiom_designated_in_countermodel :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A) phi,
    @FailureTheory A U X phi ->
    @designated (FailureConst A) (failure_countermodel X)
      (fun _ => TZero) phi.
Proof.
  intros A U X phi Hphi.
  destruct Hphi; simpl; try exact I.
  - destruct H as [p [x [t [y [Hstep Heq]]]]].
    subst phi.
    exact I.
  - intros a.
    exact I.
Qed.

Theorem failure_theory_is_nonexplosive :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A),
    ~ lp_entails (@FailureTheory A U X) (unrelated_formula X).
Proof.
  intros A U X Hexplode.
  specialize (Hexplode (failure_countermodel X) (fun _ => TZero)).
  assert (Hall :
    forall gamma, @FailureTheory A U X gamma ->
      @designated (FailureConst A) (failure_countermodel X)
        (fun _ => TZero) gamma).
  - intros gamma Hgamma.
    exact (every_failure_axiom_designated_in_countermodel Hgamma).
  - specialize (Hexplode Hall).
    exact Hexplode.
Qed.

Record FailEraseProperties (A : ComparisonCalculus) (U : UniversalMachine)
    (X : PathObject A) : Prop := {
  failerase_tc :
    forall phi, @TC (FailureConst A) U phi -> @FailureTheory A U X phi;
  failerase_conflict :
    @FailureTheory A U X (conflict_formula X);
  failerase_neg_conflict :
    @FailureTheory A U X (FNeg (conflict_formula X));
  failerase_nonexplosion :
    exists psi, ~ lp_entails (@FailureTheory A U X) psi
}.

Theorem failerase_well_defined_core :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A),
    @FailEraseProperties A U X.
Proof.
  intros A U X.
  constructor.
  - intros phi Htc.
    exact (@failure_theory_contains_TC A U X phi Htc).
  - exact (@I_Conflict A U X).
  - exact (@I_NotConflict A U X).
  - exists (unrelated_formula X).
    exact (@failure_theory_is_nonexplosive A U X).
Qed.

(** Section 16(6): an explicit legal comparison path whose raw error
    projection is not an ordinary error path. *)

Inductive C2 : Type := C0 | C1.
Inductive E2 : Type := E0 | E1.
Inductive Atom5 : Type := ABind | ARule | AModel | ATruth | ABoundary.

Definition atom5_basis : AtomicDimensionBasis.
Proof.
  refine {| AtomDim := Atom5;
            a_bind := ABind;
            a_rule := ARule;
            a_model := AModel;
            a_truth := ATruth;
            a_boundary := ABoundary |}.
  repeat constructor; simpl; intros H; repeat destruct H as [H | H];
    try discriminate; contradiction.
Defined.

Definition FreeDim : Type := DimTerm Atom5.
Definition Alpha : FreeDim := DAtom ABind.
Definition Beta : FreeDim := DAtom ARule.

Definition step_C2 (c c' : C2) : Prop :=
  match c, c' with
  | C0, C1 => True
  | _, _ => False
  end.

Definition sigma_map (s : list E2) : option (list C2) :=
  match s with
  | [E0] => Some [C0]
  | [E0; E1] => Some [C0; C1]
  | _ => None
  end.

Lemma sigma_map_cases :
  forall s cs,
    sigma_map s = Some cs ->
    (s = [E0] /\ cs = [C0]) \/
    (s = [E0; E1] /\ cs = [C0; C1]).
Proof.
  intros s cs H.
  destruct s as [| e s'].
  - discriminate.
  - destruct e.
    + destruct s' as [| e' s''].
      * left.
        inversion H.
        split; reflexivity.
      * destruct e'.
        -- discriminate.
        -- destruct s'' as [| e'' tail].
           ++ right.
              inversion H.
              split; reflexivity.
           ++ discriminate.
    + discriminate.
Qed.

Lemma sigma_map_nonempty :
  forall s cs, sigma_map s = Some cs -> s <> [].
Proof.
  intros s cs H.
  destruct (sigma_map_cases s H) as [[Hs _] | [Hs _]];
    subst s; discriminate.
Qed.

Lemma sigma_map_length :
  forall s cs, sigma_map s = Some cs -> length cs = length s.
Proof.
  intros s cs H.
  destruct (sigma_map_cases s H) as [[Hs Hcs] | [Hs Hcs]];
    subst s; subst cs; reflexivity.
Qed.

Lemma sigma_map_correct :
  forall s cs, sigma_map s = Some cs ->
    adjacent step_C2 cs.
Proof.
  intros s cs H.
  destruct (sigma_map_cases s H) as [[Hs Hcs] | [Hs Hcs]];
    subst s; subst cs; simpl; repeat split; exact I.
Qed.

Lemma sigma_map_prefix_closed :
  forall s cs m,
    sigma_map s = Some cs ->
    1 <= m <= length s ->
    exists cs', sigma_map (firstn m s) = Some cs'.
Proof.
  intros s cs m H Hm.
  destruct (sigma_map_cases s H) as [[Hs Hcs] | [Hs Hcs]].
  - subst s.
    assert (m = 1) by (simpl in Hm; lia).
    subst m.
    exists [C0].
    reflexivity.
  - subst s.
    assert (m = 1 \/ m = 2) by (simpl in Hm; lia).
    destruct H0 as [Hm1 | Hm2].
    + subst m.
      exists [C0].
      reflexivity.
    + subst m.
      exists [C0; C1].
      reflexivity.
Qed.

Lemma sigma_map_prefix_compatible :
  forall s t cs ct,
    sigma_map s = Some cs ->
    sigma_map t = Some ct ->
    s = firstn (length s) t ->
    cs = firstn (length s) ct.
Proof.
  intros s t cs ct Hs Ht Hprefix.
  destruct (sigma_map_cases s Hs) as [[Hs1 Hcs] | [Hs2 Hcs]];
  destruct (sigma_map_cases t Ht) as [[Ht1 Hct] | [Ht2 Hct]];
  subst s; subst t; subst cs; subst ct; simpl in *;
  try discriminate; reflexivity.
Qed.

Inductive RawW : Type := RW0 | RW1.

Definition raw_error_step (_ _ : E2) : Prop := False.

Definition BRaw : BottomEnvironment := {|
  Correct := C2;
  Error := E2;
  Rule := unit;
  Boundary := unit;
  correct_step := step_C2;
  ordinary_error_step := raw_error_step
|}.

Definition raw_diff (k : FreeDim) (c : C2) (e : E2) (w : RawW) : Prop :=
  match k, c, e, w with
  | DAtom ABind, C0, E0, RW0 => True
  | DAtom ABind, C1, E1, RW1 => True
  | _, _, _, _ => False
  end.

Definition raw_next (k : FreeDim) (c : C2) (e : E2)
    (c' : C2) (e' : E2) : Prop :=
  match k, c, e, c', e' with
  | DAtom ABind, C0, E0, C1, E1 => True
  | _, _, _, _, _ => False
  end.

Definition raw_pres_delta (k l : FreeDim)
    (c : C2) (e : E2) (w : RawW)
    (c' : C2) (e' : E2) (w' : RawW) : Prop :=
  match k, l, c, e, w, c', e', w' with
  | DAtom ABind, DAtom ABind, C0, E0, RW0, C1, E1, RW1 => True
  | _, _, _, _, _, _, _, _ => False
  end.

Lemma empty_dimension_congruence_is_equality :
  forall (Atom : Type) (x y : DimTerm Atom),
    dim_congruence (fun _ _ => False) x y ->
    x = y.
Proof.
  intros Atom x y H.
  induction H.
  - reflexivity.
  - contradiction.
  - symmetry.
    exact IHdim_congruence.
  - transitivity y.
    + exact IHdim_congruence1.
    + exact IHdim_congruence2.
  - rewrite IHdim_congruence1, IHdim_congruence2.
    reflexivity.
  - rewrite IHdim_congruence1, IHdim_congruence2.
    reflexivity.
  - rewrite IHdim_congruence1, IHdim_congruence2.
    reflexivity.
Qed.

Definition ARaw : ComparisonCalculus.
Proof.
  refine {|
    base := BRaw;
    dimension_basis := atom5_basis;
    dimension_equations := fun _ _ => False;
    Witness := RawW;
    Diff := raw_diff;
    Next := raw_next;
    InvDelta := raw_diff;
    InvBack := fun _ _ _ _ _ _ => False;
    PresDelta := raw_pres_delta;
    PresBack := fun _ _ _ _ _ _ _ _ _ _ _ _ => False;
    Back := fun _ _ _ _ _ => False
  |}.
  all: intros;
    repeat match goal with
    | H : dim_congruence (fun _ _ => False) ?x ?y |- _ =>
        apply empty_dimension_congruence_is_equality in H; subst
    end;
    tauto.
Defined.

Definition raw_sigma : @PathSelector ARaw :=
  @Build_PathSelector ARaw sigma_map
    sigma_map_nonempty
    sigma_map_length
    sigma_map_correct
    sigma_map_prefix_closed
    sigma_map_prefix_compatible.

Definition PRaw : list (CNode ARaw) :=
  [@mkCNode ARaw C0 E0 Alpha RW0;
   @mkCNode ARaw C1 E1 Alpha RW1].

Lemma raw_path_is_legal : legal_path raw_sigma PRaw.
Proof.
  unfold legal_path, PRaw, raw_sigma.
  simpl.
  split.
  - discriminate.
  - split.
    + reflexivity.
    + split.
      * constructor.
        -- split; exact I.
        -- constructor.
           ++ split; exact I.
           ++ constructor.
      * split.
        -- split; exact I.
        -- split; exact I.
Qed.

Theorem raw_erase_may_be_nonordinary :
  legal_path raw_sigma PRaw /\
  ~ ordinary_error_path (base ARaw) (RawErase (LegalObject PRaw)).
Proof.
  split.
  - exact raw_path_is_legal.
  - unfold ordinary_error_path, RawErase, ErrSeq, PRaw.
    simpl.
    intros [H _].
    exact H.
Qed.

(** Section 17: the explicit comparison-separation model. *)

Lemma alpha_and_beta_are_distinct_in_the_free_algebra :
  ~ dim_congruence (fun _ _ => False) Alpha Beta.
Proof.
  intros H.
  pose proof (empty_dimension_congruence_is_equality H) as Heq.
  discriminate Heq.
Qed.

Inductive Rule2 : Type := RAlpha | RBeta.
Inductive Boundary2 : Type := BAlpha | BBeta.
Inductive SepW : Type := SU0 | SU1 | SV0 | SV1.

Definition sep_error_step (e e' : E2) : Prop :=
  match e, e' with
  | E0, E1 => True
  | _, _ => False
  end.

Definition BSep : BottomEnvironment := {|
  Correct := C2;
  Error := E2;
  Rule := Rule2;
  Boundary := Boundary2;
  correct_step := step_C2;
  ordinary_error_step := sep_error_step
|}.

Definition sep_diff (k : FreeDim) (c : C2) (e : E2) (w : SepW) : Prop :=
  match k, c, e, w with
  | DAtom ABind, C0, E0, SU0 => True
  | DAtom ABind, C1, E1, SU1 => True
  | DAtom ARule, C0, E0, SV0 => True
  | DAtom ARule, C1, E1, SV1 => True
  | _, _, _, _ => False
  end.

Definition sep_next (k : FreeDim) (c : C2) (e : E2)
    (c' : C2) (e' : E2) : Prop :=
  match k, c, e, c', e' with
  | DAtom ABind, C0, E0, C1, E1 => True
  | DAtom ARule, C0, E0, C1, E1 => True
  | _, _, _, _, _ => False
  end.

Definition sep_pres_delta (k l : FreeDim)
    (c : C2) (e : E2) (w : SepW)
    (c' : C2) (e' : E2) (w' : SepW) : Prop :=
  match k, l, c, e, w, c', e', w' with
  | DAtom ABind, DAtom ABind, C0, E0, SU0, C1, E1, SU1 => True
  | DAtom ARule, DAtom ARule, C0, E0, SV0, C1, E1, SV1 => True
  | _, _, _, _, _, _, _, _ => False
  end.

Definition sep_back (k : FreeDim) (c : C2) (e : E2)
    (b : Boundary2) (r : Rule2) : Prop :=
  match k, c, e, b, r with
  | DAtom ABind, C0, E0, BAlpha, RAlpha => True
  | DAtom ABind, C1, E1, BAlpha, RAlpha => True
  | DAtom ARule, C0, E0, BBeta, RBeta => True
  | DAtom ARule, C1, E1, BBeta, RBeta => True
  | _, _, _, _, _ => False
  end.

Definition sep_inv_back (k : FreeDim) (c : C2) (e : E2) (w : SepW)
    (b : Boundary2) (r : Rule2) : Prop :=
  match k, c, e, w, b, r with
  | DAtom ABind, C0, E0, SU0, BAlpha, RAlpha => True
  | DAtom ABind, C1, E1, SU1, BAlpha, RAlpha => True
  | DAtom ARule, C0, E0, SV0, BBeta, RBeta => True
  | DAtom ARule, C1, E1, SV1, BBeta, RBeta => True
  | _, _, _, _, _, _ => False
  end.

Definition sep_pres_back (k l : FreeDim)
    (c : C2) (e : E2) (w : SepW) (b : Boundary2) (r : Rule2)
    (c' : C2) (e' : E2) (w' : SepW) (b' : Boundary2) (r' : Rule2)
    : Prop :=
  match k, l, c, e, w, b, r, c', e', w', b', r' with
  | DAtom ABind, DAtom ABind,
    C0, E0, SU0, BAlpha, RAlpha,
    C1, E1, SU1, BAlpha, RAlpha => True
  | DAtom ARule, DAtom ARule,
    C0, E0, SV0, BBeta, RBeta,
    C1, E1, SV1, BBeta, RBeta => True
  | _, _, _, _, _, _, _, _, _, _, _, _ => False
  end.

Definition ASep : ComparisonCalculus.
Proof.
  refine {|
    base := BSep;
    dimension_basis := atom5_basis;
    dimension_equations := fun _ _ => False;
    Witness := SepW;
    Diff := sep_diff;
    Next := sep_next;
    InvDelta := sep_diff;
    InvBack := sep_inv_back;
    PresDelta := sep_pres_delta;
    PresBack := sep_pres_back;
    Back := sep_back
  |}.
  all: intros;
    repeat match goal with
    | H : dim_congruence (fun _ _ => False) ?x ?y |- _ =>
        apply empty_dimension_congruence_is_equality in H; subst
    end;
    tauto.
Defined.

Definition sep_sigma : @PathSelector ASep :=
  @Build_PathSelector ASep sigma_map
    sigma_map_nonempty
    sigma_map_length
    sigma_map_correct
    sigma_map_prefix_closed
    sigma_map_prefix_compatible.

Definition PCompare : list (CNode ASep) :=
  [@mkCNode ASep C0 E0 Alpha SU0;
   @mkCNode ASep C1 E1 Alpha SU1].

Definition QCompare : list (CNode ASep) :=
  [@mkCNode ASep C0 E0 Beta SV0;
   @mkCNode ASep C1 E1 Beta SV1].

Lemma pcompare_is_legal : legal_path sep_sigma PCompare.
Proof.
  unfold legal_path, PCompare, sep_sigma.
  simpl.
  split.
  - discriminate.
  - split.
    + reflexivity.
    + split.
      * constructor.
        -- split; exact I.
        -- constructor.
           ++ split; exact I.
           ++ constructor.
      * split.
        -- split; exact I.
        -- split; exact I.
Qed.

Lemma qcompare_is_legal : legal_path sep_sigma QCompare.
Proof.
  unfold legal_path, QCompare, sep_sigma.
  simpl.
  split.
  - discriminate.
  - split.
    + reflexivity.
    + split.
      * constructor.
        -- split; exact I.
        -- constructor.
           ++ split; exact I.
           ++ constructor.
      * split.
        -- split; exact I.
        -- split; exact I.
Qed.

Definition RhoP : list (BackInterface ASep) :=
  [(BAlpha, RAlpha); (BAlpha, RAlpha)].

Definition RhoQ : list (BackInterface ASep) :=
  [(BBeta, RBeta); (BBeta, RBeta)].

Definition PBackWitness : PathBackElement ASep :=
  (DSeq Alpha Alpha, RhoP).

Definition QBackWitness : PathBackElement ASep :=
  (DSeq Beta Beta, RhoQ).

Lemma pcompare_back_witness :
  PathBack PCompare PBackWitness.
Proof.
  unfold PathBack, PBackWitness.
  exists (DSeq Alpha Alpha), RhoP.
  split.
  - reflexivity.
  - split.
    + reflexivity.
    + unfold BackTrace, PCompare, RhoP.
      simpl.
      repeat split; exact I.
Qed.

Lemma qcompare_back_witness :
  PathBack QCompare QBackWitness.
Proof.
  unfold PathBack, QBackWitness.
  exists (DSeq Beta Beta), RhoQ.
  split.
  - reflexivity.
  - split.
    + reflexivity.
    + unfold BackTrace, QCompare, RhoQ.
      simpl.
      repeat split; exact I.
Qed.

Lemma qcompare_excludes_p_back_witness :
  ~ PathBack QCompare PBackWitness.
Proof.
  intros H.
  unfold PathBack in H.
  destruct H as [d [rho [Hz [Hfold _]]]].
  unfold PBackWitness in Hz.
  inversion Hz.
  subst d.
  unfold DimFold, QCompare, DimSeq in Hfold.
  simpl in Hfold.
  discriminate.
Qed.

Definition same_predicate_set {A : Type} (S T : A -> Prop) : Prop :=
  forall x, S x <-> T x.

Lemma comparison_back_spaces_differ :
  ~ same_predicate_set (PathBack PCompare) (PathBack QCompare).
Proof.
  intros Heq.
  apply qcompare_excludes_p_back_witness.
  apply (proj1 (Heq PBackWitness)).
  exact pcompare_back_witness.
Qed.

Lemma comparison_dimension_classes_differ :
  ~ quotient_dimseq_equiv PCompare QCompare.
Proof.
  unfold quotient_dimseq_equiv, DimSeq.
  simpl.
  intros H.
  inversion H as [| alpha beta ps qs Halpha Htail].
  apply alpha_and_beta_are_distinct_in_the_free_algebra.
  exact Halpha.
Qed.

Theorem comparison_separation :
  exists P Q : list (CNode ASep),
    legal_path sep_sigma P /\
    legal_path sep_sigma Q /\
    ordinary_failure_equiv (LegalObject P) (LegalObject Q) /\
    ~ quotient_dimseq_equiv P Q /\
    ~ same_predicate_set (PathBack P) (PathBack Q).
Proof.
  exists PCompare, QCompare.
  split.
  - exact pcompare_is_legal.
  - split.
    + exact qcompare_is_legal.
    + split.
      * reflexivity.
      * split.
        -- exact comparison_dimension_classes_differ.
        -- exact comparison_back_spaces_differ.
Qed.

(** The statement in the source compares the outputs of [FailErase_sigma],
    whose inputs are already known to be legal.  This certified relation makes
    that domain information explicit while observing exactly [OrdObs]. *)
Definition certified_failerase_ordinary_equiv
    {A : ComparisonCalculus} {sigma : PathSelector A}
    (CX CY : @CertifiedPathObject A sigma) : Prop :=
  ordinary_failure_equiv (certified_object CX) (certified_object CY).

Definition PCompareCertified : @CertifiedPathObject ASep sep_sigma :=
  @Build_CertifiedPathObject ASep sep_sigma
    (LegalObject PCompare) pcompare_is_legal.

Definition QCompareCertified : @CertifiedPathObject ASep sep_sigma :=
  @Build_CertifiedPathObject ASep sep_sigma
    (LegalObject QCompare) qcompare_is_legal.

Theorem faithful_comparison_separation :
  exists CP CQ : @CertifiedPathObject ASep sep_sigma,
    certified_failerase_ordinary_equiv CP CQ /\
    ~ quotient_dimseq_equiv
        (object_prefix (certified_object CP))
        (object_prefix (certified_object CQ)) /\
    ~ same_predicate_set
        (PathBack (object_prefix (certified_object CP)))
        (PathBack (object_prefix (certified_object CQ))).
Proof.
  exists PCompareCertified, QCompareCertified.
  split.
  - reflexivity.
  - split.
    + exact comparison_dimension_classes_differ.
    + exact comparison_back_spaces_differ.
Qed.

(** Additional faithfulness lemmas for partial reasons and dynamic languages. *)

Theorem failed_attempt_builds_a_canonical_noise_record :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         P cstar estar lambda,
    legal_path sigma P ->
    fail_attempt sigma P cstar estar lambda ->
    exists nu,
      canonical_noise_record sigma P cstar estar lambda = Some nu /\
      valid_noise_record sigma nu.
Proof.
  intros A sigma P cstar estar lambda Hlegal Hfail.
  destruct (failed_attempt_reason_is_defined Hlegal Hfail) as [q Hq].
  exists (@mkNoiseRecord A P cstar estar lambda
    (ErrSeq P ++ [estar]) (CorrSeq P ++ [cstar]) q).
  split.
  - unfold canonical_noise_record.
    rewrite Hq.
    reflexivity.
  - unfold valid_noise_record.
    simpl.
    split.
    + exact Hlegal.
    + split.
      * exact Hfail.
      * split.
        -- reflexivity.
        -- split.
           ++ reflexivity.
           ++ exact Hq.
Qed.

Lemma valid_noise_reason_zero_records_no_difference :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (nu : NoiseRecord A),
    valid_noise_record sigma nu ->
    noise_reason nu = 0 ->
    forall w,
      ~ Diff A (noise_dimension nu) (noise_correct nu) (noise_error nu) w.
Proof.
  intros A sigma nu Hvalid Hzero.
  destruct Hvalid as [_ [_ [_ [_ Hreason]]]].
  apply (proj1 (@reason_zero_iff_no_diff A sigma
    (noise_prefix nu) (noise_correct nu) (noise_error nu)
    (noise_dimension nu))).
  rewrite Hreason, Hzero.
  reflexivity.
Qed.

Lemma valid_noise_reason_one_records_failed_invariant_or_preservation :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (nu : NoiseRecord A),
    valid_noise_record sigma nu ->
    noise_reason nu = 1 ->
    (exists w,
      Diff A (noise_dimension nu) (noise_correct nu) (noise_error nu) w) /\
    ~ (exists w,
      extension_witness (noise_prefix nu)
        (noise_correct nu) (noise_error nu) (noise_dimension nu) w).
Proof.
  intros A sigma nu Hvalid Hone.
  destruct Hvalid as [_ [_ [_ [_ Hreason]]]].
  apply (proj1
    (@reason_one_iff_diff_but_no_valid_extension_witness A sigma
      (noise_prefix nu) (noise_correct nu) (noise_error nu)
      (noise_dimension nu))).
  rewrite Hreason, Hone.
  reflexivity.
Qed.

Theorem failure_theory_formulas_are_well_formed :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A) phi,
    @FailureTheory A U X phi ->
    wf_formula phi.
Proof.
  intros A U X phi Hphi.
  destruct Hphi; simpl; try reflexivity.
  destruct H as [p [x [t [y [_ Heq]]]]].
  subst phi.
  reflexivity.
Qed.

Lemma numerals_use_no_dynamic_constants :
  forall (A : ComparisonCalculus) (X : PathObject A) n,
    term_in_failure_language X (@numeral (FailureConst A) n).
Proof.
  intros A X n.
  induction n as [| n IH].
  - exact I.
  - simpl.
    exact IH.
Qed.

Theorem failure_theory_uses_only_its_dynamic_language :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A) phi,
    @FailureTheory A U X phi ->
    formula_in_failure_language X phi.
Proof.
  intros A U X phi Hphi.
  destruct Hphi; subst; simpl;
    repeat constructor;
    eauto using InFailureLanguage, numerals_use_no_dynamic_constants.
  all: try (destruct H as [p [x [t [y [_ Heq]]]]]; subst phi; simpl;
    repeat constructor; apply numerals_use_no_dynamic_constants).
  all: try (econstructor; [left; eassumption | eassumption]).
  all: try (econstructor; left; eassumption).
Qed.

Lemma lp_entails_monotone :
  forall (Const : Type) (Gamma Delta : Theory Const) phi,
    (forall gamma, Gamma gamma -> Delta gamma) ->
    lp_entails Gamma phi ->
    lp_entails Delta phi.
Proof.
  intros Const Gamma Delta phi Hsubset Hentails M g Hall.
  apply Hentails.
  intros gamma Hgamma.
  apply Hall.
  exact (Hsubset gamma Hgamma).
Qed.

Theorem failure_theory_entails_each_true_utm_computation :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A) p x t y,
    UTM U p x t y ->
    lp_entails (@FailureTheory A U X)
      (@halts_formula (FailureConst A) p x y).
Proof.
  intros A U X p x t y Hstep.
  eapply lp_entails_monotone.
  - intros gamma Htc.
    exact (@I_TC A U X gamma Htc).
  - exact (@tc_entails_halts (FailureConst A) U p x t y Hstep).
Qed.

Theorem every_failure_theory_expresses_universal_computation :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (X : PathObject A) (f : nat -> nat -> Prop),
    PartialRecursive U f ->
    exists p, forall x y,
      f x y ->
      lp_entails (@FailureTheory A U X)
        (@halts_formula (FailureConst A) p x y).
Proof.
  intros A U X f Hrecursive.
  destruct (universal_program U f Hrecursive) as [p Hp].
  exists p.
  intros x y Hf.
  apply (proj1 (Hp x y)) in Hf.
  destruct Hf as [t Hstep].
  exact (@failure_theory_entails_each_true_utm_computation
    A U X p x t y Hstep).
Qed.

Lemma unrelated_formula_is_well_formed :
  forall (A : ComparisonCalculus) (X : PathObject A),
    wf_formula (unrelated_formula X).
Proof.
  intros A X.
  reflexivity.
Qed.

Lemma unrelated_formula_belongs_to_failure_language :
  forall (A : ComparisonCalculus) (X : PathObject A),
    formula_in_failure_language X (unrelated_formula X).
Proof.
  intros A X.
  simpl.
  constructor.
  - exact (LangPath X).
  - constructor.
Qed.

Record FaithfulFailEraseProperties
    (A : ComparisonCalculus) (sigma : PathSelector A)
    (U : UniversalMachine) (CX : @CertifiedPathObject A sigma) : Prop := {
  faithful_core :
    @FailEraseProperties A U (certified_object CX);
  faithful_reflection_source :
    @ReflectionProvenance A sigma (certified_object CX);
  faithful_language_exact : forall c,
    @fe_language A (certified_object CX) (@FailErase A sigma U CX) c <->
    InFailureLanguage (certified_object CX) c;
  faithful_theory_exact : forall phi,
    @fe_theory A (certified_object CX) (@FailErase A sigma U CX) phi <->
    @FailureTheory A U (certified_object CX) phi;
  faithful_theory_internal : forall phi,
    @FailureTheory A U (certified_object CX) phi ->
    formula_in_failure_language (certified_object CX) phi;
  faithful_consequence_exact : forall Gamma phi,
    @fe_consequence A (certified_object CX) (@FailErase A sigma U CX)
      Gamma phi <->
    @lp_entails (FailureConst A) Gamma phi
}.

Theorem faithful_failerase_well_defined_core :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (U : UniversalMachine) (CX : @CertifiedPathObject A sigma),
    @FaithfulFailEraseProperties A sigma U CX.
Proof.
  intros A sigma U CX.
  constructor.
  - exact (@failerase_well_defined_core A U (certified_object CX)).
  - exact (@failerase_source_has_reflection_provenance A sigma U CX).
  - intros c.
    reflexivity.
  - intros phi.
    reflexivity.
  - intros phi Hphi.
    exact (@failure_theory_is_internal_to_dynamic_language
      A U (certified_object CX) phi Hphi).
  - intros Gamma phi.
    reflexivity.
Qed.

(** The node formulas in [I_sigma(X)] are not free-standing annotations:
    for a certified source they are backed by the actual calculus relations. *)
Theorem certified_node_reflection_bundle :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (U : UniversalMachine) (CX : @CertifiedPathObject A sigma)
         i node,
    nth_error (object_prefix (certified_object CX)) i = Some node ->
    @FailureTheory A U (certified_object CX)
      (FAtom PDiff [tdim i node; tcorr i node; terr i node; twit i node]) /\
    @FailureTheory A U (certified_object CX)
      (FAtom PCmp [tdim i node; tcorr i node; terr i node]) /\
    @FailureTheory A U (certified_object CX)
      (FAtom PInvD [tdim i node; tcorr i node; terr i node; twit i node]) /\
    Diff A (node_dimension node) (node_correct node) (node_error node)
      (node_witness node) /\
    InvDelta A (node_dimension node) (node_correct node) (node_error node)
      (node_witness node) /\
    @obj_derives A
      (CmpAt (node_dimension node) (node_correct node) (node_error node)).
Proof.
  intros A sigma U CX i node Hnth.
  pose proof (@failerase_source_has_reflection_provenance
    A sigma U CX) as Hsource.
  destruct Hsource as [Hdiff Hinv Hcmp Hnext Hpres].
  repeat split.
  - exact (@I_Diff A U (certified_object CX) i node Hnth).
  - exact (@I_Cmp A U (certified_object CX) i node Hnth).
  - exact (@I_InvD A U (certified_object CX) i node Hnth).
  - exact (Hdiff i node Hnth).
  - exact (Hinv i node Hnth).
  - exact (Hcmp i node Hnth).
Qed.

(** Likewise, each adjacent-step formula is generated from a genuine
    [Next]/[PresDelta] step of the certified comparison path. *)
Theorem certified_step_reflection_bundle :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (U : UniversalMachine) (CX : @CertifiedPathObject A sigma)
         i node next_node,
    nth_error (object_prefix (certified_object CX)) i = Some node ->
    nth_error (object_prefix (certified_object CX)) (S i) = Some next_node ->
    @FailureTheory A U (certified_object CX)
      (FAtom PNextPair
        [tx (certified_object CX); numeral i; tdim i node;
         tcorr i node; terr i node;
         tcorr (S i) next_node; terr (S i) next_node]) /\
    @FailureTheory A U (certified_object CX)
      (FAtom PPresD
        [tdim i node; tdim (S i) next_node;
         tcorr i node; terr i node; twit i node;
         tcorr (S i) next_node; terr (S i) next_node;
         twit (S i) next_node]) /\
    node_next node next_node /\
    node_pres_delta node next_node.
Proof.
  intros A sigma U CX i node next_node Hnth Hnextnth.
  pose proof (@failerase_source_has_reflection_provenance
    A sigma U CX) as Hsource.
  destruct Hsource as [Hdiff Hinv Hcmp Hnext Hpres].
  repeat split.
  - exact (@I_NextPair A U (certified_object CX)
      i node next_node Hnth Hnextnth).
  - exact (@I_PresD A U (certified_object CX)
      i node next_node Hnth Hnextnth).
  - exact (Hnext i node next_node Hnth Hnextnth).
  - exact (Hpres i node next_node Hnth Hnextnth).
Qed.

Theorem certified_noise_zero_schema_is_truthful :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (U : UniversalMachine) (CX : @CertifiedPathObject A sigma)
         nu,
    certified_object CX = NoiseObject nu ->
    noise_reason nu = 0 ->
    @FailureTheory A U (certified_object CX)
      (FForall 0
        (FNeg (FAtom PDiff
          [TConst (FCStarDimension (noise_dimension nu));
           TConst (FCStarCorrect (noise_correct nu));
           TConst (FCStarError (noise_error nu));
           TVar 0]))) /\
    forall w,
      ~ Diff A (noise_dimension nu) (noise_correct nu) (noise_error nu) w.
Proof.
  intros A sigma U CX nu HX Hzero.
  split.
  - exact (@I_NoDiffReason A U (certified_object CX) nu HX Hzero).
  - pose proof (certified_object_valid CX) as Hvalid.
    rewrite HX in Hvalid.
    exact (@valid_noise_reason_zero_records_no_difference
      A sigma nu Hvalid Hzero).
Qed.

Theorem certified_noise_one_schema_is_truthful :
  forall (A : ComparisonCalculus) (sigma : PathSelector A)
         (U : UniversalMachine) (CX : @CertifiedPathObject A sigma)
         nu,
    certified_object CX = NoiseObject nu ->
    noise_reason nu = 1 ->
    @FailureTheory A U (certified_object CX)
      (FAtom PNoiseRecord
        [tx (certified_object CX); numeral (length (noise_prefix nu));
         TConst (FCStarDimension (noise_dimension nu));
         TConst (FCStarCorrect (noise_correct nu));
         TConst (FCStarError (noise_error nu));
         numeral 1]) /\
    (exists w,
      Diff A (noise_dimension nu) (noise_correct nu) (noise_error nu) w) /\
    ~ (exists w,
      extension_witness (noise_prefix nu)
        (noise_correct nu) (noise_error nu) (noise_dimension nu) w).
Proof.
  intros A sigma U CX nu HX Hone.
  split.
  - exact (@I_ReasonOne A U (certified_object CX) nu HX Hone).
  - pose proof (certified_object_valid CX) as Hvalid.
    rewrite HX in Hvalid.
    exact (@valid_noise_reason_one_records_failed_invariant_or_preservation
      A sigma nu Hvalid Hone).
Qed.

Theorem theorem1_core_for_valid_objects :
  forall (A : ComparisonCalculus) (U : UniversalMachine)
         (sigma : PathSelector A) (X : PathObject A)
         (Hvalid : valid_object sigma X),
    @FaithfulFailEraseProperties A sigma U
      (@Build_CertifiedPathObject A sigma X Hvalid).
Proof.
  intros A U sigma X Hvalid.
  exact (@faithful_failerase_well_defined_core A sigma U
    (@Build_CertifiedPathObject A sigma X Hvalid)).
Qed.

Print Assumptions faithful_failerase_well_defined_core.
Print Assumptions certified_node_reflection_bundle.
Print Assumptions certified_step_reflection_bundle.
Print Assumptions certified_noise_zero_schema_is_truthful.
Print Assumptions certified_noise_one_schema_is_truthful.
Print Assumptions raw_erase_may_be_nonordinary.
Print Assumptions faithful_comparison_separation.
End ErrorReflectionTheory1528.
