(* PSCA 2170 — self-contained all-in-one formalization. *)
(* Generated by dependency-ordered textual inlining of the verified modules. *)
(* No declaration, rule, model, theorem, or proof body is altered. *)

(* ================================================================= *)
(* Inlined verbatim from PSCA2170_Core.v; only internal PSCA Require removed. *)
(* ================================================================= *)
(*
  PSCA 2.3 core (note 2170), sections 1--7.
  Fixed primitive-recursive/ZFC data are explicit record fields.  Theorems
  claimed by the source are proved outside those records.
*)
From Stdlib Require Import List Bool Arith PeanoNat ZArith Lia Relations Sorting.Sorted Classes.RelationClasses.
Import ListNotations.
Set Implicit Arguments.

Inductive psca_ty : Type :=
| TyStr | TyCfg | TyRun | TyTree | TyCert | TyEdge | TyPath | TyCell
| TyAbElem | TySubgrp | TyProtocol | TyLicArr | TyModel | TyPoint
| TySource | TyFrame | TySite | TySourceCx | TyFill | TyNoFill
| TyCurv | TyChain | TyRuleName | TyTok | TyCtx | TyDer | TyAsm
| TyReachState | TyOp | TyEvent.

Definition psca_ty_eq_dec : forall x y : psca_ty, {x = y} + {x <> y}.
Proof. decide equality. Defined.

Record tagged_code := Tag { code_type : psca_ty; code_payload : nat }.

Lemma different_tags_are_disjoint :
  forall t u m n, t <> u -> Tag t m <> Tag u n.
Proof.
  intros t u m n Hneq Heq.
  inversion Heq.
  contradiction.
Qed.

Definition word := list nat.
Definition cantor_pair (m n : nat) : nat :=
  ((m + n) * (m + n + 1)) / 2 + n.

Record forest_certificate := ForestCertificate {
  cert_word : word;
  cert_forest : list nat;
  cert_runs : list nat;
  cert_cover_proof : nat
}.

Definition strictly_increasing (xs : list nat) : Prop :=
  StronglySorted lt xs.

Record generator_data := GeneratorData {
  cfg_ok : nat -> Prop;
  init_cfg : word -> nat;
  step_g : nat -> nat -> nat -> Prop;
  halt_tree_g : nat -> nat -> Prop;
  tree_g : nat -> Prop;
  comp_run_g : word -> nat -> nat -> Prop;
  trace_g : nat -> nat -> nat -> nat -> Prop;
  phi_g : nat -> nat -> nat -> Prop;
  trace_characterizes_phi :
    forall e u v, phi_g e u v <-> exists r, trace_g e u r v;
  prefix_trace_g : nat -> nat -> nat -> Prop;
  emit_g : nat -> nat -> word;
  nat_word_g : nat -> word;
  emit_injective :
    forall a b c d, emit_g a b = emit_g c d -> a = c /\ b = d;
  prf_h : nat -> nat -> Prop;
  coverage_code : word -> list nat -> nat;
  coverage_sound :
    forall w F pi, prf_h pi (coverage_code w F) ->
    forall r t, comp_run_g w r t -> In t F;
  verifier : forest_certificate -> bool;
  verifier_spec : forall c,
    verifier c = true <->
      cert_forest c <> [] /\
      NoDup (cert_forest c) /\
      strictly_increasing (cert_forest c) /\
      Forall2 (comp_run_g (cert_word c)) (cert_runs c) (cert_forest c) /\
      prf_h (cert_cover_proof c)
        (coverage_code (cert_word c) (cert_forest c));
  nu_g : nat -> nat;
  nu_injective : forall x y, nu_g x = nu_g y -> x = y;
  nu_node_parity : forall t, Nat.odd (nu_g t) = Nat.odd t
}.

Definition V (G : generator_data) (c : forest_certificate) : bool :=
  verifier G c.

Fixpoint parity_count (G : generator_data) (odd : bool) (F : list nat) : nat :=
  match F with
  | [] => 0
  | t :: ts =>
      (if Bool.eqb (Nat.odd (nu_g G t)) odd then 1 else 0) +
      parity_count G odd ts
  end.

Definition Prof2 (G : generator_data) (c : forest_certificate) : nat * nat :=
  (parity_count G false (cert_forest c),
   parity_count G true (cert_forest c)).

Definition Gate2 (G : generator_data) (c : forest_certificate) : Prop :=
  fst (Prof2 G c) = snd (Prof2 G c) /\ 0 < fst (Prof2 G c).

Definition SemCert (G : generator_data) (c : forest_certificate) : Prop :=
  V G c = true /\ Gate2 G c.

Lemma Forall2_right_witness :
  forall (A B : Type) (R : A -> B -> Prop) xs ys y,
    Forall2 R xs ys -> In y ys ->
    exists x, In x xs /\ R x y.
Proof.
  intros A B R xs ys y H.
  induction H as [|x y0 xs ys Hxy Hrest IH].
  - intros Hin. contradiction.
  - intros [Heq | Hin].
    + subst y0. exists x. split.
      * left. reflexivity.
      * exact Hxy.
    + destruct (IH Hin) as [x' [Hinx' HR]].
      exists x'. split.
      * right. exact Hinx'.
      * exact HR.
Qed.

Theorem verified_forest_is_exact :
  forall G c t, V G c = true ->
    ((exists r, comp_run_g G (cert_word c) r t) <->
     In t (cert_forest c)).
Proof.
  intros G c t HV.
  apply (verifier_spec G c) in HV.
  destruct HV as [_ [_ [_ [Hruns Hcover]]]].
  split.
  - intros [r Hrun].
    eapply coverage_sound.
    + exact Hcover.
    + exact Hrun.
  - intro Hin.
    destruct (@Forall2_right_witness nat nat (comp_run_g G (cert_word c)) (cert_runs c) (cert_forest c) t Hruns Hin) as [r [_ Hrun]].
    exists r.
    exact Hrun.
Qed.

Inductive edge_dir := Forward | Backward.
Record raw_edge := RawEdge {
  edge_name : nat;
  edge_address : nat;
  edge_source_tree : nat;
  edge_target_tree : nat;
  edge_direction : edge_dir;
  edge_source_letter : nat
}.
Record raw_path := RawPath {
  path_start : nat;
  path_finish : nat;
  path_edges : list raw_edge
}.
Definition closed_path (p : raw_path) : Prop :=
  path_start p = path_finish p.

Inductive source_kind := Monitor | Slot.
Inductive signed_source := SrcPos (s : nat) | SrcNeg (s : nat).

Record source_complex := SourceComplex {
  sc_certificate_code : nat;
  sc_sites : list nat;
  sc_cells : list nat;
  sc_initial_sites : list nat;
  sc_root : nat;
  sc_kind : nat -> option source_kind;
  sc_color : nat -> option nat;
  sc_anchor : nat -> option nat;
  sc_frame : nat -> option nat;
  sc_active : nat -> option bool;
  sc_attachment : nat -> option nat;
  sc_birth : nat -> option nat;
  sc_boundary : nat -> option nat;
  sc_source_word : nat -> option (list signed_source)
}.

Definition incidence (K : source_complex) (x y : nat) : Prop :=
  (In x (sc_sites K) /\ In y (sc_cells K) /\
   sc_attachment K y = Some x) \/
  (In x (sc_cells K) /\ In y (sc_sites K) /\
   sc_birth K y = Some x).

Definition acyclic {A : Type} (R : A -> A -> Prop) : Prop :=
  forall x, ~ clos_trans A R x x.

Definition SourceCxWF (K : source_complex) : Prop :=
  NoDup (sc_sites K) /\ NoDup (sc_cells K) /\
  (forall x, In x (sc_sites K) -> ~ In x (sc_cells K)) /\
  In (sc_root K) (sc_sites K) /\
  sc_kind K (sc_root K) = Some Monitor /\
  sc_active K (sc_root K) = Some true /\
  (forall z, In z (sc_sites K) -> exists k, sc_kind K z = Some k) /\
  (forall z, In z (sc_sites K) -> exists s, sc_color K z = Some s) /\
  (forall z, In z (sc_sites K) -> exists r, sc_frame K z = Some r) /\
  (forall z, In z (sc_sites K) -> exists a, sc_active K z = Some a) /\
  (forall z, In z (sc_sites K) -> sc_kind K z = Some Slot ->
     exists t, sc_anchor K z = Some t) /\
  (forall x z, sc_attachment K x = Some z ->
     In x (sc_cells K) /\ sc_kind K z = Some Slot) /\
  (forall x, In x (sc_cells K) -> exists z, sc_attachment K x = Some z) /\
  (forall x, In x (sc_cells K) -> exists h, sc_boundary K x = Some h) /\
  (forall x, In x (sc_cells K) -> exists w, sc_source_word K x = Some w) /\
  (forall x y z, sc_attachment K x = Some z ->
     sc_attachment K y = Some z -> x = y) /\
  (forall z x, sc_birth K z = Some x ->
     In z (sc_sites K) /\ ~ In z (sc_initial_sites K) /\
     In x (sc_cells K)) /\
  (forall z, In z (sc_sites K) -> ~ In z (sc_initial_sites K) ->
     exists x, sc_birth K z = Some x) /\
  acyclic (incidence K) /\
  (forall z, sc_kind K z = Some Monitor -> sc_birth K z = None) /\
  (forall z, In z (sc_sites K) -> sc_kind K z = Some Slot ->
     (sc_active K z = Some true <->
      ~ exists x, sc_attachment K x = Some z)).

Record finite_group := FiniteGroup {
  fg_carrier : list nat;
  fg_e : nat;
  fg_mul : nat -> nat -> nat;
  fg_inv : nat -> nat;
  fg_closed_mul : forall x y,
    In x fg_carrier -> In y fg_carrier -> In (fg_mul x y) fg_carrier;
  fg_closed_inv : forall x, In x fg_carrier -> In (fg_inv x) fg_carrier;
  fg_assoc : forall x y z,
    In x fg_carrier -> In y fg_carrier -> In z fg_carrier ->
    fg_mul x (fg_mul y z) = fg_mul (fg_mul x y) z;
  fg_left_id : forall x, In x fg_carrier -> fg_mul fg_e x = x;
  fg_right_id : forall x, In x fg_carrier -> fg_mul x fg_e = x;
  fg_left_inv : forall x, In x fg_carrier -> fg_mul (fg_inv x) x = fg_e;
  fg_right_inv : forall x, In x fg_carrier -> fg_mul x (fg_inv x) = fg_e
}.

(*
  This is the source's fixed finite/primitive-recursive data interface:
  chains and Smith--Hermite quotient codes, canonical source complexes,
  attachment, finite filler enumeration, finite models and synchronized
  quotients.  Every operational clause used by a rule is visible here.
*)
Definition coded_path_equiv
    (chain : forest_certificate -> raw_path -> nat)
    (eta : forest_certificate -> nat -> nat)
    (c : forest_certificate) (p q : raw_path) : Prop :=
  path_start p = path_start q /\ path_finish p = path_finish q /\
  eta c (chain c p) = eta c (chain c q).
Record psca_kernel := PSCAKernel {
  pk_generator : generator_data;
  pk_group : finite_group;
  pk_source_value : signed_source -> nat;
  pk_source_inverse : forall s,
    pk_source_value (SrcNeg s) =
    fg_inv pk_group (pk_source_value (SrcPos s));
  pk_gen : nat -> list signed_source -> nat -> list (nat * nat);
  pk_source_word : raw_path -> list signed_source;
  pk_rho : raw_path -> nat;
  pk_first_nonbottom : list signed_source -> option nat;
  pk_rho_empty : forall t, pk_rho (RawPath t t []) = fg_e pk_group;

  pk_path_ok : forest_certificate -> raw_path -> Prop;
  pk_path_chain : forest_certificate -> raw_path -> nat;
  pk_chain_add : forest_certificate -> nat -> nat -> nat;
  pk_chain_neg : forest_certificate -> nat -> nat;
  pk_reflect2 : raw_path -> raw_path -> Prop;
  pk_eta : forest_certificate -> nat -> nat;
  pk_B2 : forest_certificate -> nat -> Prop;
  pk_eta_rep : forest_certificate -> nat -> nat;
  pk_eta_section : forall c a, pk_eta c (pk_eta_rep c a) = a;
  pk_eta_kernel : forall c x y,
    pk_eta c x = pk_eta c y <->
    pk_B2 c (pk_chain_add c x (pk_chain_neg c y));

  pk_path_id : nat -> raw_path;
  pk_path_comp : raw_path -> raw_path -> raw_path;
  pk_path_inv : raw_path -> raw_path;
  pk_path_id_spec : forall c t,
    pk_path_ok c (pk_path_id t) /\
    path_start (pk_path_id t) = t /\ path_finish (pk_path_id t) = t;
  pk_path_comp_spec : forall c p q,
    pk_path_ok c p -> pk_path_ok c q -> path_finish p = path_start q ->
    pk_path_ok c (pk_path_comp p q) /\
    path_start (pk_path_comp p q) = path_start p /\
    path_finish (pk_path_comp p q) = path_finish q /\
    pk_path_chain c (pk_path_comp p q) =
      pk_chain_add c (pk_path_chain c p) (pk_path_chain c q);
  pk_path_inv_spec : forall c p,
    pk_path_ok c p ->
    pk_path_ok c (pk_path_inv p) /\
    path_start (pk_path_inv p) = path_finish p /\
    path_finish (pk_path_inv p) = path_start p /\
    pk_path_chain c (pk_path_inv p) = pk_chain_neg c (pk_path_chain c p);
  pk_path_comp_respects : forall c p p' q q',
    coded_path_equiv pk_path_chain pk_eta c p p' ->
    coded_path_equiv pk_path_chain pk_eta c q q' ->
    coded_path_equiv pk_path_chain pk_eta c
      (pk_path_comp p q) (pk_path_comp p' q');
  pk_path_assoc : forall c p q r,
    coded_path_equiv pk_path_chain pk_eta c
      (pk_path_comp (pk_path_comp p q) r)
      (pk_path_comp p (pk_path_comp q r));
  pk_path_left_id : forall c p,
    coded_path_equiv pk_path_chain pk_eta c
      (pk_path_comp (pk_path_id (path_start p)) p) p;
  pk_path_right_id : forall c p,
    coded_path_equiv pk_path_chain pk_eta c
      (pk_path_comp p (pk_path_id (path_finish p))) p;
  pk_path_left_inv : forall c p,
    coded_path_equiv pk_path_chain pk_eta c
      (pk_path_comp (pk_path_inv p) p) (pk_path_id (path_finish p));
  pk_path_right_inv : forall c p,
    coded_path_equiv pk_path_chain pk_eta c
      (pk_path_comp p (pk_path_inv p)) (pk_path_id (path_start p));

  pk_can : source_complex -> source_complex;
  pk_can_wf : forall K, SourceCxWF K -> SourceCxWF (pk_can K);
  pk_can_idempotent : forall K, pk_can (pk_can K) = pk_can K;
  pk_canonical_fields_extensional : forall K L,
    pk_can K = K -> pk_can L = L ->
    (forall i k s a r act,
      (sc_kind K i = Some k /\ sc_color K i = Some s /\
       sc_anchor K i = a /\ sc_frame K i = Some r /\
       sc_active K i = Some act) <->
      (sc_kind L i = Some k /\ sc_color L i = Some s /\
       sc_anchor L i = a /\ sc_frame L i = Some r /\
       sc_active L i = Some act)) ->
    (forall j i h w,
      (sc_attachment K j = Some i /\ sc_boundary K j = Some h /\
       sc_source_word K j = Some w) <->
      (sc_attachment L j = Some i /\ sc_boundary L j = Some h /\
       sc_source_word L j = Some w)) ->
    (forall i j, sc_birth K i = Some j <-> sc_birth L i = Some j) ->
    K = L;
  pk_initial : forest_certificate -> option source_complex;
  pk_initial_spec : forall c K,
    pk_initial c = Some K -> SemCert pk_generator c /\ SourceCxWF K;
  pk_attach : forest_certificate -> source_complex -> nat -> raw_path ->
    option source_complex;
  pk_attach_spec : forall c K sigma p K',
    pk_attach c K sigma p = Some K' ->
    SourceCxWF K /\ SourceCxWF K' /\ closed_path p /\
    sc_kind K sigma = Some Slot /\ sc_active K sigma = Some true /\
    sc_anchor K sigma = Some (path_start p);
  pk_attach_literal_spec : forall c K sigma p K',
    pk_attach c K sigma p = Some K' ->
    exists new_cell jZ jC new_sites old_color old_frame old_anchor,
      sc_color K sigma = Some old_color /\
      sc_frame K sigma = Some old_frame /\
      sc_anchor K sigma = Some old_anchor /\
      pk_first_nonbottom (pk_source_word p) = Some old_color /\
      sc_cells K' = map jC (sc_cells K) ++ [new_cell] /\
      sc_sites K' = map jZ (sc_sites K) ++ new_sites /\
      sc_root K' = jZ (sc_root K) /\
      sc_attachment K' new_cell = Some (jZ sigma) /\
      sc_boundary K' new_cell =
        Some (pk_eta c (pk_path_chain c p)) /\
      sc_source_word K' new_cell = Some (pk_source_word p) /\
      sc_active K' (jZ sigma) = Some false /\
      (forall z r, In z (sc_sites K) -> sc_frame K z = Some r ->
        sc_frame K' (jZ z) = Some (fg_mul pk_group (pk_rho p) r)) /\
      (forall x z, sc_attachment K x = Some z ->
        sc_attachment K' (jC x) = Some (jZ z)) /\
      (forall z x, sc_birth K z = Some x ->
        sc_birth K' (jZ z) = Some (jC x)) /\
      (forall x h, sc_boundary K x = Some h ->
        sc_boundary K' (jC x) = Some h) /\
      (forall x w, sc_source_word K x = Some w ->
        sc_source_word K' (jC x) = Some w) /\
      Forall2
        (fun z cr =>
          sc_kind K' z = Some Slot /\
          sc_color K' z = Some (fst cr) /\
          sc_anchor K' z = Some old_anchor /\
          sc_frame K' z =
            Some (fg_mul pk_group (snd cr)
              (fg_mul pk_group (pk_rho p) old_frame)) /\
          sc_active K' z = Some true /\
          sc_birth K' z = Some new_cell)
        new_sites (pk_gen old_color (pk_source_word p) old_frame);

  pk_N : forest_certificate -> source_complex -> nat;
  pk_subgroup_member : nat -> nat -> Prop;
  pk_subgroup_add : nat -> nat -> nat;
  pk_cyclic_subgroup : nat -> nat;
  pk_B : forest_certificate -> source_complex -> nat -> Prop;
  pk_B_spec : forall c K v,
    pk_B c K v <-> pk_subgroup_member (pk_N c K) (pk_eta c v);
  pk_N_attach : forall c K sigma p K',
    pk_attach c K sigma p = Some K' ->
    pk_N c K' = pk_subgroup_add (pk_N c K)
      (pk_cyclic_subgroup (pk_eta c (pk_path_chain c p)));
  pk_state_eta : forest_certificate -> source_complex -> nat -> nat;
  pk_quotient : source_complex -> source_complex -> nat -> nat;
  pk_quotient_comp : forall K K' K'' v,
    pk_quotient K' K'' (pk_quotient K K' v) = pk_quotient K K'' v;
  pk_Omega : source_complex -> list (signed_source * nat);
  pk_parikh : list signed_source -> list (signed_source * nat);
  pk_spectrum_add : list (signed_source * nat) ->
    list (signed_source * nat) -> list (signed_source * nat);
  pk_Omega_attach : forall c K sigma p K',
    pk_attach c K sigma p = Some K' ->
    pk_Omega K' = pk_spectrum_add (pk_Omega K) (pk_parikh (pk_source_word p));

  pk_filler_table : source_complex -> nat -> raw_path -> nat -> raw_path ->
    nat -> Prop;
  pk_filler : source_complex -> nat -> raw_path -> nat -> raw_path -> Prop;
  pk_filler_spec : forall K s p t q,
    pk_filler K s p t q <-> exists phi, pk_filler_table K s p t q phi;
  pk_nofill_check : source_complex -> nat -> raw_path -> nat -> raw_path ->
    nat -> bool;
  pk_fill_or_nofill : forall K s p t q,
    (exists phi, pk_filler_table K s p t q phi) \/
    (exists d, pk_nofill_check K s p t q d = true);
  pk_fill_nofill_exclusive : forall K s p t q phi d,
    pk_filler_table K s p t q phi ->
    pk_nofill_check K s p t q d = true -> False;
  pk_curv : source_complex -> raw_path -> raw_path -> nat;
  pk_curv_spec : forall K p q,
    pk_curv K p q =
      fg_mul pk_group (fg_mul pk_group (pk_rho q) (pk_rho p))
        (fg_inv pk_group (fg_mul pk_group (pk_rho p) (pk_rho q)));

  pk_model_ok : forest_certificate -> nat -> Prop;
  pk_qual : forest_certificate -> nat -> Prop;
  pk_qual_spec : forall c M,
    pk_qual c M -> SemCert pk_generator c /\ pk_model_ok c M;
  pk_instance : forest_certificate -> nat -> source_complex -> nat -> nat -> Prop;
  pk_transport : forest_certificate -> nat -> source_complex ->
    raw_path -> nat -> option nat;
  pk_model_quotient : forest_certificate -> nat -> source_complex -> nat;
  pk_sync_square : forall c M K s p t q Kpq Kqp,
    pk_attach c K s p = Some Kpq ->
    pk_attach c K t q = Some Kqp ->
    pk_model_quotient c M Kpq = pk_model_quotient c M Kqp;

  pk_form : source_complex -> nat -> Prop;
  pk_form_spec : forall K u,
    pk_form K u <-> sc_frame K (sc_root K) = Some u;
  pk_seed : nat -> nat -> word;
  pk_seed_spec : forall u n, pk_seed u n = emit_g pk_generator u n;
  pk_relation_witness : forest_certificate -> source_complex -> nat -> nat -> Prop;
  pk_square_ready : source_complex -> nat -> raw_path -> nat -> raw_path -> Prop;
  pk_square_ready_spec : forall K s p t q,
    pk_square_ready K s p t q ->
    exists cs ct fs ft,
      s <> t /\ closed_path p /\ closed_path q /\
      sc_kind K s = Some Slot /\ sc_kind K t = Some Slot /\
      sc_active K s = Some true /\ sc_active K t = Some true /\
      sc_color K s = Some cs /\ sc_color K t = Some ct /\
      sc_frame K s = Some fs /\ sc_frame K t = Some ft /\
      pk_first_nonbottom (pk_source_word p) = Some cs /\
      pk_first_nonbottom (pk_source_word q) = Some ct /\
      pk_gen cs (pk_source_word p) fs = [] /\
      pk_gen ct (pk_source_word q) ft = [];
  pk_compare : source_complex -> nat -> raw_path -> nat -> raw_path ->
    (nat + (nat * nat));
  pk_compare_spec : forall K s p t q,
    match pk_compare K s p t q with
    | inl phi => pk_filler_table K s p t q phi
    | inr (kappa, d) =>
        pk_nofill_check K s p t q d = true /\ kappa = pk_curv K p q
    end
}.

Inductive ReachCx (P : psca_kernel) (c : forest_certificate) :
    source_complex -> Prop :=
| ReachCx_initial : forall K,
    pk_initial P c = Some K -> ReachCx P c K
| ReachCx_attach : forall K sigma p K',
    ReachCx P c K ->
    pk_attach P c K sigma p = Some K' ->
    ReachCx P c K'.

Definition PathEquiv (P : psca_kernel) (c : forest_certificate)
    (p q : raw_path) : Prop :=
  coded_path_equiv (pk_path_chain P) (pk_eta P) c p q.

Theorem PathEquiv_is_equivalence :
  forall P c, Equivalence (PathEquiv P c).
Proof.
  intros P c. constructor.
  - intro p. repeat split; reflexivity.
  - intros p q [Hs [Ht He]]. repeat split; symmetry; assumption.
  - intros p q r [Hs1 [Ht1 He1]] [Hs2 [Ht2 He2]].
    repeat split; congruence.
Qed.

Definition respects_license_relation (P : psca_kernel)
    (c : forest_certificate) (D : Type) (f : nat -> D) : Prop :=
  forall x y, pk_eta P c x = pk_eta P c y -> f x = f y.

Definition factors_through_eta (P : psca_kernel)
    (c : forest_certificate) (D : Type)
    (f : nat -> D) (bar : nat -> D) : Prop :=
  forall x, bar (pk_eta P c x) = f x.

Definition unique_eta_factor (P : psca_kernel)
    (c : forest_certificate) (D : Type) (f : nat -> D) : Prop :=
  exists bar : nat -> D,
    factors_through_eta P c f bar /\
    forall bar', factors_through_eta P c f bar' ->
      forall a, bar' a = bar a.

Theorem license_quotient_universal :
  forall P c D (f : nat -> D),
    respects_license_relation P c f <->
    unique_eta_factor P c f.
Proof.
  intros P c D f. split.
  - intro Hrespect.
    exists (fun a => f (pk_eta_rep P c a)).
    split.
    + intro x. apply Hrespect. apply pk_eta_section.
    + intros bar' Hbar' a.
      specialize (Hbar' (pk_eta_rep P c a)).
      rewrite (pk_eta_section P c a) in Hbar'.
      exact Hbar'.
  - intros [bar [Hbar _]] x y Heq.
    rewrite <- (Hbar x), <- (Hbar y), Heq.
    reflexivity.
Qed.

Definition Form (P : psca_kernel) := pk_form P.
Definition Fut (P : psca_kernel) (K : source_complex) : nat -> word -> Prop :=
  fun r w => exists n, pk_form P K r /\ w = pk_seed P r n.


(* ================================================================= *)
(* Inlined verbatim from PSCA2170_Rules.v; only internal PSCA Require removed. *)
(* ================================================================= *)
(* PSCA 2.3, sections 8--10: tokens, rules, derivations, events. *)
From Stdlib Require Import List Bool Arith PeanoNat Relations.
Import ListNotations.
Set Implicit Arguments.

Inductive token_payload : Type :=
| RawCertP (c : forest_certificate)
| CertTokP (c : forest_certificate)
| CxTokP (c : forest_certificate) (K : source_complex)
| ModelTokP (c : forest_certificate) (M : nat) (K : source_complex)
| NonceP (n : nat)
| PathTokP (c : forest_certificate) (K : source_complex)
    (p : raw_path) (h nonce : nat)
| InstTokP (c : forest_certificate) (M : nat) (K : source_complex)
    (tree point nonce : nat)
| SeedTokP (c : forest_certificate) (M : nat) (K : source_complex)
    (sigma : nat) (p : raw_path) (h program nonce : nat)
| AttachTokP (c : forest_certificate) (K : source_complex)
    (sigma : nat) (p : raw_path) (K' : source_complex)
| RelTokP (c : forest_certificate) (K : source_complex) (v witness : nat)
| FillTokP (c : forest_certificate) (K : source_complex)
    (sigma : nat) (p : raw_path) (tau : nat) (q : raw_path) (phi : nat)
| CurvTokP (c : forest_certificate) (K : source_complex)
    (sigma : nat) (p : raw_path) (tau : nat) (q : raw_path)
    (kappa nofill : nat)
| FormTokP (c : forest_certificate) (K : source_complex) (rule : nat)
| RuleSeedTokP (c : forest_certificate) (K : source_complex)
    (rule nonce : nat)
| LossTokP (exchange loss : list (signed_source * nat))
| OutTokP (s : word)
| BoundaryTokP (program input prefix : nat).

(*
  Correction of the source's omitted identifier coordinate: a token is a
  globally unique natural identifier plus exactly one displayed payload.
*)
Record token := Token { token_id : nat; token_body : token_payload }.

Definition persistent_payload (p : token_payload) : Prop :=
  match p with
  | CertTokP _ | CxTokP _ _ | ModelTokP _ _ _ => True
  | _ => False
  end.

Definition persistent_payloadb (p : token_payload) : bool :=
  match p with
  | CertTokP _ | CxTokP _ _ | ModelTokP _ _ _ => true
  | _ => false
  end.

Lemma persistent_payloadb_spec : forall p,
  persistent_payloadb p = true <-> persistent_payload p.
Proof.
  intro p.
  destruct p; cbn; split; intro H; try discriminate;
    try contradiction; try exact I; reflexivity.
Qed.

Record context := Context {
  ctx_history : list (nat * nat);
  ctx_persistent : list token;
  ctx_linear : list token
}.

Definition ids (xs : list token) : list nat := map token_id xs.

Definition ContextWF (G : context) : Prop :=
  NoDup (ids (ctx_persistent G ++ ctx_linear G)) /\
  (forall t, In t (ctx_persistent G) -> persistent_payload (token_body t)) /\
  (forall t, In t (ctx_linear G) -> ~ persistent_payload (token_body t)) /\
  (forall t, In t (ctx_persistent G) -> ~ In t (ctx_linear G)) /\
  acyclic (fun x y => In (x, y) (ctx_history G)).

Definition initial_context (G : context) : Prop :=
  ContextWF G /\ ctx_persistent G = [] /\
  exists c raw nonces,
    token_body raw = RawCertP c /\
    (forall t, In t nonces -> exists n, token_body t = NonceP n) /\
    ctx_linear G = raw :: nonces /\
    ctx_history G = [].

Definition same_members {A : Type} (xs ys : list A) : Prop :=
  forall x, In x xs <-> In x ys.

Definition parent_edges (inputs outputs : list token) : list (nat * nat) :=
  flat_map
    (fun i => map (fun o => (token_id i, token_id o)) outputs)
    inputs.

Definition context_update (G G' : context)
    (consumed read outputs : list token) : Prop :=
  ContextWF G /\ ContextWF G' /\
  (forall t, In t consumed -> In t (ctx_linear G)) /\
  (forall t, In t read -> In t (ctx_persistent G)) /\
  NoDup (ids outputs) /\
  (forall o, In o outputs ->
     ~ In (token_id o) (ids (ctx_persistent G ++ ctx_linear G))) /\
  same_members (ctx_persistent G')
    (ctx_persistent G ++ filter (fun t => persistent_payloadb (token_body t)) outputs) /\
  (forall t,
    In t (ctx_linear G') <->
      (In t (ctx_linear G) /\ ~ In t consumed) \/
      (In t outputs /\ ~ persistent_payload (token_body t))) /\
  same_members (ctx_history G')
    (ctx_history G ++ parent_edges (consumed ++ read) outputs).

Inductive op : Type :=
| VERIFY | ADMIT_MODEL | ISSUE_PATH | PLACE | ASSEMBLE | MATERIALIZE
| PROVE_REL | COMPARE_ORDER | FORM_OP | FEEDBACK_FORM
| FEEDBACK_TRACE | BOUNDARY_PREFIX.

Inductive Rule (P : psca_kernel) :
    context -> op -> context -> list token -> Prop :=
| Rule_VERIFY : forall G G' c raw certtok cxtok K0,
    In raw (ctx_linear G) -> token_body raw = RawCertP c ->
    SemCert (pk_generator P) c -> pk_initial P c = Some K0 ->
    token_body certtok = CertTokP c -> token_body cxtok = CxTokP c K0 ->
    context_update G G' [raw] [] [certtok; cxtok] ->
    Rule P G VERIFY G' [certtok; cxtok]
| Rule_ADMIT : forall G G' c K M certtok cxtok modeltok,
    In certtok (ctx_persistent G) -> token_body certtok = CertTokP c ->
    In cxtok (ctx_persistent G) -> token_body cxtok = CxTokP c K ->
    pk_qual P c M -> token_body modeltok = ModelTokP c M K ->
    context_update G G' [] [certtok; cxtok] [modeltok] ->
    Rule P G ADMIT_MODEL G' [modeltok]
| Rule_ISSUE : forall G G' c K n nonce p h cxtok pathtok,
    In cxtok (ctx_persistent G) -> token_body cxtok = CxTokP c K ->
    In nonce (ctx_linear G) -> token_body nonce = NonceP n ->
    pk_path_ok P c p -> h = pk_state_eta P c K (pk_path_chain P c p) ->
    token_body pathtok = PathTokP c K p h n ->
    context_update G G' [nonce] [cxtok] [pathtok] ->
    Rule P G ISSUE_PATH G' [pathtok]
| Rule_PLACE : forall G G' c M K t x n modeltok nonce insttok,
    In modeltok (ctx_persistent G) ->
    token_body modeltok = ModelTokP c M K ->
    pk_instance P c M K t x ->
    In nonce (ctx_linear G) -> token_body nonce = NonceP n ->
    token_body insttok = InstTokP c M K t x n ->
    context_update G G' [nonce] [modeltok] [insttok] ->
    Rule P G PLACE G' [insttok]
| Rule_ASSEMBLE : forall G G' c M K t x nx p h np modeltok pathtok insttok
      sigma e y outinst seedtok,
    In modeltok (ctx_persistent G) ->
    token_body modeltok = ModelTokP c M K ->
    In pathtok (ctx_linear G) ->
    token_body pathtok = PathTokP c K p h np ->
    In insttok (ctx_linear G) ->
    token_body insttok = InstTokP c M K t x nx ->
    path_start p = t -> pk_transport P c M K p x = Some y ->
    sc_kind K sigma = Some Slot -> sc_active K sigma = Some true ->
    pk_first_nonbottom P (pk_source_word P p) = sc_color K sigma ->
    token_body outinst = InstTokP c M K (path_finish p) y nx ->
    token_body seedtok = SeedTokP c M K sigma p h e np ->
    context_update G G' [pathtok; insttok] [modeltok] [outinst; seedtok] ->
    Rule P G ASSEMBLE G' [outinst; seedtok]
| Rule_MATERIALIZE : forall G G' c M K sigma p h e n K'
      seed cxtok modeltok newcx newmodel attach,
    In seed (ctx_linear G) ->
    token_body seed = SeedTokP c M K sigma p h e n ->
    closed_path p -> pk_attach P c K sigma p = Some K' ->
    In cxtok (ctx_persistent G) -> token_body cxtok = CxTokP c K ->
    In modeltok (ctx_persistent G) ->
    token_body modeltok = ModelTokP c M K ->
    token_body newcx = CxTokP c K' ->
    token_body newmodel = ModelTokP c M K' ->
    token_body attach = AttachTokP c K sigma p K' ->
    context_update G G' [seed] [cxtok; modeltok] [newcx; newmodel; attach] ->
    Rule P G MATERIALIZE G' [newcx; newmodel; attach]
| Rule_PROVE_REL : forall G G' c K n v w nonce cxtok reltok,
    In cxtok (ctx_persistent G) -> token_body cxtok = CxTokP c K ->
    In nonce (ctx_linear G) -> token_body nonce = NonceP n ->
    pk_relation_witness P c K v w ->
    token_body reltok = RelTokP c K v w ->
    context_update G G' [nonce] [cxtok] [reltok] ->
    Rule P G PROVE_REL G' [reltok]
| Rule_COMPARE_FILL : forall G G' c M K s p hp ep np t q hq eq nq
      seedp seedq phi filltok,
    In seedp (ctx_linear G) ->
    token_body seedp = SeedTokP c M K s p hp ep np ->
    In seedq (ctx_linear G) ->
    token_body seedq = SeedTokP c M K t q hq eq nq ->
    pk_square_ready P K s p t q ->
    pk_compare P K s p t q = inl phi ->
    token_body filltok = FillTokP c K s p t q phi ->
    context_update G G' [seedp; seedq] [] [filltok] ->
    Rule P G COMPARE_ORDER G' [filltok]
| Rule_COMPARE_CURV : forall G G' c M K s p hp ep np t q hq eq nq
      seedp seedq kappa d curvtok,
    In seedp (ctx_linear G) ->
    token_body seedp = SeedTokP c M K s p hp ep np ->
    In seedq (ctx_linear G) ->
    token_body seedq = SeedTokP c M K t q hq eq nq ->
    pk_square_ready P K s p t q ->
    pk_compare P K s p t q = inr (kappa, d) ->
    token_body curvtok = CurvTokP c K s p t q kappa d ->
    context_update G G' [seedp; seedq] [] [curvtok] ->
    Rule P G COMPARE_ORDER G' [curvtok]
| Rule_FORM : forall G G' c K u n cxtok nonce formtok ruletok,
    In cxtok (ctx_persistent G) -> token_body cxtok = CxTokP c K ->
    In nonce (ctx_linear G) -> token_body nonce = NonceP n ->
    pk_form P K u -> token_body formtok = FormTokP c K u ->
    token_body ruletok = RuleSeedTokP c K u n ->
    context_update G G' [nonce] [cxtok] [formtok; ruletok] ->
    Rule P G FORM_OP G' [formtok; ruletok]
| Rule_FEEDBACK_FORM : forall G G' c K u n ruletok outtok,
    In ruletok (ctx_linear G) ->
    token_body ruletok = RuleSeedTokP c K u n ->
    token_body outtok = OutTokP (pk_seed P u n) ->
    context_update G G' [ruletok] [] [outtok] ->
    Rule P G FEEDBACK_FORM G' [outtok]
| Rule_FEEDBACK_TRACE : forall G G' c M K s p h e n seed u r v outtok,
    In seed (ctx_linear G) ->
    token_body seed = SeedTokP c M K s p h e n ->
    trace_g (pk_generator P) e u r v ->
    token_body outtok = OutTokP
      (emit_g (pk_generator P)
        (cantor_pair (cert_cover_proof c) (sc_root K)) (cantor_pair u v)) ->
    context_update G G' [seed] [] [outtok] ->
    Rule P G FEEDBACK_TRACE G' [outtok]
| Rule_BOUNDARY : forall G G' c M K s p h e n seed u q newseed boundary,
    In seed (ctx_linear G) ->
    token_body seed = SeedTokP c M K s p h e n ->
    prefix_trace_g (pk_generator P) e u q ->
    token_body newseed = SeedTokP c M K s p h e n ->
    token_body boundary = BoundaryTokP e u q ->
    context_update G G' [seed] [] [newseed; boundary] ->
    Rule P G BOUNDARY_PREFIX G' [newseed; boundary].

Inductive Der (P : psca_kernel) :
    context -> list (op * list token) -> context -> Prop :=
| Der_zero : forall G, initial_context G -> Der P G [] G
| Der_snoc : forall G0 tr G op0 G' outputs,
    Der P G0 tr G -> Rule P G op0 G' outputs ->
    Der P G0 (tr ++ [(op0, outputs)]) G'.

Definition reachable (P : psca_kernel) (G G' : context) : Prop :=
  exists tr, Der P G tr G'.

Record reach_state (P : psca_kernel) := ReachState {
  rs_certificate : forest_certificate;
  rs_model : nat;
  rs_complex : source_complex;
  rs_start_context : context;
  rs_end_context : context;
  rs_trace : list (op * list token);
  rs_derivation : Der P rs_start_context rs_trace rs_end_context;
  rs_cx_present : exists t, In t (ctx_persistent rs_end_context) /\
    token_body t = CxTokP rs_certificate rs_complex;
  rs_model_present : exists t, In t (ctx_persistent rs_end_context) /\
    token_body t = ModelTokP rs_certificate rs_model rs_complex
}.

(*
  The source says twelve-tuple but displays thirteen semantic coordinates:
  c,M,K,sigma,t,t',x,y,p,h,e,n,D.  They are all fields below; proof contexts
  are additional typing evidence, not extra semantic coordinates.
*)
Record assembly (P : psca_kernel) := Assembly {
  asm_certificate : forest_certificate;
  asm_model : nat;
  asm_complex : source_complex;
  asm_slot : nat;
  asm_source_tree : nat;
  asm_target_tree : nat;
  asm_source_point : nat;
  asm_target_point : nat;
  asm_path : raw_path;
  asm_chain : nat;
  asm_program : nat;
  asm_nonce : nat;
  asm_derivation_code : list (op * list token);
  asm_start_context : context;
  asm_prefix_context : context;
  asm_final_context : context;
  asm_outputs : list token;
  asm_prefix_derivation :
    Der P asm_start_context asm_derivation_code asm_prefix_context;
  asm_last_is_assemble :
    Rule P asm_prefix_context ASSEMBLE asm_final_context asm_outputs;
  asm_canonical : pk_can P asm_complex = asm_complex;
  asm_path_source : path_start asm_path = asm_source_tree;
  asm_path_target : path_finish asm_path = asm_target_tree;
  asm_transport :
    pk_transport P asm_certificate asm_model asm_complex asm_path
      asm_source_point = Some asm_target_point
}.

Definition closed_assembly {P} (A : assembly P) : Prop :=
  closed_path (asm_path A).

Definition assembly_interface {P} (A : assembly P) :=
  (asm_certificate A, asm_model A, asm_source_tree A,
   asm_target_tree A, asm_source_point A).

Inductive event : Type :=
| QualEv
| BaseRelEv (v : nat)
| NowEv (point parity : nat)
| AttachRelEv (v : nat)
| SiteEv (site : nat) (kind : source_kind) (color : nat)
    (anchor : option nat) (frame : nat) (active : bool)
| CellEv (cell site boundary : nat) (sources : list signed_source)
| BirthEv (site cell : nat)
| FormEv (rule : nat)
| FillEv (sigma : nat) (p : raw_path) (tau : nat) (q : raw_path)
| CurvEv (sigma : nat) (p : raw_path) (tau : nat) (q : raw_path)
    (kappa : nat)
| HaltOutEv (input output : nat).

Definition event_holds {P} (A : assembly P) (ev : event) : Prop :=
  match ev with
  | QualEv => pk_qual P (asm_certificate A) (asm_model A)
  | BaseRelEv v => pk_B P (asm_certificate A) (asm_complex A) v
  | NowEv b parity =>
      b = asm_target_point A /\
      parity = Nat.modulo (nu_g (pk_generator P) (asm_target_tree A)) 2
  | AttachRelEv v =>
      exists K', pk_attach P (asm_certificate A) (asm_complex A)
        (asm_slot A) (asm_path A) = Some K' /\
        pk_B P (asm_certificate A) K' v
  | SiteEv i k s a r act =>
      sc_kind (asm_complex A) i = Some k /\
      sc_color (asm_complex A) i = Some s /\
      sc_anchor (asm_complex A) i = a /\
      sc_frame (asm_complex A) i = Some r /\
      sc_active (asm_complex A) i = Some act
  | CellEv j i h w =>
      sc_attachment (asm_complex A) j = Some i /\
      sc_boundary (asm_complex A) j = Some h /\
      sc_source_word (asm_complex A) j = Some w
  | BirthEv i j => sc_birth (asm_complex A) i = Some j
  | FormEv r => pk_form P (asm_complex A) r
  | FillEv s p t q => pk_filler P (asm_complex A) s p t q
  | CurvEv s p t q k =>
      ~ pk_filler P (asm_complex A) s p t q /\
      k = pk_curv P (asm_complex A) p q
  | HaltOutEv u v => phi_g (pk_generator P) (asm_program A) u v
  end.

Definition ObsEq {P} (A B : assembly P) : Prop :=
  forall ev, event_holds A ev <-> event_holds B ev.

Definition PathCompEv {P} (A0 A1 A2 : assembly P) : Prop :=
  asm_target_tree A0 = asm_source_tree A1 /\
  asm_source_tree A0 = asm_source_tree A2 /\
  asm_target_tree A1 = asm_target_tree A2 /\
  asm_chain A2 = pk_chain_add P (asm_certificate A0)
    (asm_chain A1) (asm_chain A0).

Definition QuotCompEv (P : psca_kernel)
    (K K' K'' : source_complex) : Prop :=
  forall v,
    pk_quotient P K' K'' (pk_quotient P K K' v) =
    pk_quotient P K K'' v.

Inductive lift_result := LiftFill | LiftCurv (kappa : nat).
Definition LiftSqEv (P : psca_kernel) (K : source_complex)
    (sigma : nat) (p : raw_path) (tau : nat) (q : raw_path)
    (result : lift_result) : Prop :=
  match result with
  | LiftFill => pk_filler P K sigma p tau q
  | LiftCurv k => ~ pk_filler P K sigma p tau q /\
                    k = pk_curv P K p q
  end.

Record beta_equal {P} (A B : assembly P) : Prop := BetaEqual {
  beta_complex : asm_complex A = asm_complex B;
  beta_now : asm_target_point A = asm_target_point B;
  beta_next_rel : forall v,
    (exists K', pk_attach P (asm_certificate A) (asm_complex A)
       (asm_slot A) (asm_path A) = Some K' /\
       pk_B P (asm_certificate A) K' v) <->
    (exists K', pk_attach P (asm_certificate B) (asm_complex B)
       (asm_slot B) (asm_path B) = Some K' /\
       pk_B P (asm_certificate B) K' v);
  beta_program : forall u v,
    phi_g (pk_generator P) (asm_program A) u v <->
    phi_g (pk_generator P) (asm_program B) u v
}.

Definition same_interface {P} (A B : assembly P) : Prop :=
  asm_certificate A = asm_certificate B /\
  asm_model A = asm_model B /\
  asm_source_tree A = asm_source_tree B /\
  asm_target_tree A = asm_target_tree B /\
  asm_source_point A = asm_source_point B /\
  asm_slot A = asm_slot B /\ asm_path A = asm_path B.

Definition canonical_event_extensionality (P : psca_kernel) : Prop :=
  forall A B : assembly P,
    (forall i k s a r act,
      event_holds A (SiteEv i k s a r act) <->
      event_holds B (SiteEv i k s a r act)) ->
    (forall j i h w,
      event_holds A (CellEv j i h w) <->
      event_holds B (CellEv j i h w)) ->
    (forall i j,
      event_holds A (BirthEv i j) <->
      event_holds B (BirthEv i j)) ->
    asm_complex A = asm_complex B.

Lemma kernel_canonical_event_extensionality :
  forall P, canonical_event_extensionality P.
Proof.
  intros P A B Hsite Hcell Hbirth.
  apply (pk_canonical_fields_extensional P).
  - exact (asm_canonical A).
  - exact (asm_canonical B).
  - intros i k s a r act. exact (Hsite i k s a r act).
  - intros j i h w. exact (Hcell j i h w).
  - intros i j. exact (Hbirth i j).
Qed.
Lemma observation_implies_beta :
  forall P (A B : assembly P),
    same_interface A B -> canonical_event_extensionality P ->
    ObsEq A B -> beta_equal A B.
Proof.
  intros P A B Hif Hcanonical Hobs.
  destruct Hif as [Hc [Hm [Ht [Ht' [Hx [Hs Hp]]]]]].
  assert (HK : asm_complex A = asm_complex B).
  - apply Hcanonical.
    + intros. apply Hobs.
    + intros. apply Hobs.
    + intros. apply Hobs.
  - constructor.
    + exact HK.
    + specialize (Hobs (NowEv (asm_target_point A)
        (Nat.modulo (nu_g (pk_generator P) (asm_target_tree A)) 2))).
      apply (proj1 Hobs).
      split.
      * reflexivity.
      * reflexivity.
    + intro v. exact (Hobs (AttachRelEv v)).
    + intros u v. exact (Hobs (HaltOutEv u v)).
Qed.

Lemma beta_implies_observation :
  forall P (A B : assembly P),
    same_interface A B -> beta_equal A B -> ObsEq A B.
Proof.
  intros P A B Hif Hbeta ev.
  destruct Hif as [Hc [Hm [Ht [Ht' [Hx [Hs Hp]]]]]].
  destruct Hbeta as [HK Hnow Hnext Hprog].
  destruct ev; cbn.
  - now rewrite Hc, Hm.
  - now rewrite Hc, HK.
  - rewrite Hnow, Ht'. tauto.
  - apply Hnext.
  - now rewrite HK.
  - now rewrite HK.
  - now rewrite HK.
  - now rewrite HK.
  - now rewrite HK.
  - now rewrite HK.
  - apply Hprog.
Qed.

Theorem observational_equivalence_iff_beta :
  forall P (A B : assembly P),
    same_interface A B ->
    (ObsEq A B <-> beta_equal A B).
Proof.
  intros P A B Hif.
  split.
  - apply observation_implies_beta.
    + exact Hif.
    + apply kernel_canonical_event_extensionality.
  - apply beta_implies_observation.
    exact Hif.
Qed.


(* ================================================================= *)
(* Inlined verbatim from PSCA2170_Prototype.v; only internal PSCA Require removed. *)
(* ================================================================= *)
(* PSCA 2.3, sections 11--12: executable finite model and no-flatness. *)
From Stdlib Require Import List Bool Arith PeanoNat ZArith Lia.
Import ListNotations.
Set Implicit Arguments.

Inductive s3 : Type := S3e | S3a01 | S3b12 | S3c02 | S3ba | S3ab.

Definition s3_eq_dec : forall x y : s3, {x = y} + {x <> y}.
Proof. decide equality. Defined.

(* x*y means x after y.  S3ba=(12)(01), S3ab=(01)(12). *)
Definition s3_mul (x y : s3) : s3 :=
  match x, y with
  | S3e, z => z
  | z, S3e => z
  | S3a01, S3a01 => S3e
  | S3a01, S3b12 => S3ab
  | S3a01, S3c02 => S3ba
  | S3a01, S3ba => S3c02
  | S3a01, S3ab => S3b12
  | S3b12, S3a01 => S3ba
  | S3b12, S3b12 => S3e
  | S3b12, S3c02 => S3ab
  | S3b12, S3ba => S3a01
  | S3b12, S3ab => S3c02
  | S3c02, S3a01 => S3ab
  | S3c02, S3b12 => S3ba
  | S3c02, S3c02 => S3e
  | S3c02, S3ba => S3b12
  | S3c02, S3ab => S3a01
  | S3ba, S3a01 => S3b12
  | S3ba, S3b12 => S3c02
  | S3ba, S3c02 => S3a01
  | S3ba, S3ba => S3ab
  | S3ba, S3ab => S3e
  | S3ab, S3a01 => S3c02
  | S3ab, S3b12 => S3a01
  | S3ab, S3c02 => S3b12
  | S3ab, S3ba => S3e
  | S3ab, S3ab => S3ba
  end.

Definition s3_inv (x : s3) : s3 :=
  match x with
  | S3e => S3e | S3a01 => S3a01 | S3b12 => S3b12 | S3c02 => S3c02
  | S3ba => S3ab | S3ab => S3ba
  end.

Lemma s3_associative : forall x y z,
  s3_mul x (s3_mul y z) = s3_mul (s3_mul x y) z.
Proof. intros x y z; destruct x, y, z; reflexivity. Qed.

Lemma s3_identity : forall x,
  s3_mul S3e x = x /\ s3_mul x S3e = x.
Proof. intro x; destruct x; split; reflexivity. Qed.

Lemma s3_inverse : forall x,
  s3_mul (s3_inv x) x = S3e /\ s3_mul x (s3_inv x) = S3e.
Proof. intro x; destruct x; split; reflexivity. Qed.

Lemma source_transpositions_do_not_commute :
  s3_mul S3b12 S3a01 <> s3_mul S3a01 S3b12.
Proof. discriminate. Qed.

Inductive proto_edge := EdgeA | EdgeB | EdgeD | LoopAlpha | LoopBeta.
Definition theta_z2 (_ : proto_edge) : bool := true.
Definition z2_add := xorb.

(* The only initial 2-cell has boundary a-b; in Z2, 1-1=0. *)
Lemma prototype_reflection_respected :
  z2_add (theta_z2 EdgeA) (theta_z2 EdgeB) = false.
Proof. reflexivity. Qed.

Record proto_Z5 := ProtoZ5 {
  p5_a : Z; p5_b : Z; p5_d : Z; p5_alpha : Z; p5_beta : Z
}.

Record proto_Z4 := ProtoZ4 {
  p4_ab : Z; p4_d : Z; p4_alpha : Z; p4_beta : Z
}.

Definition proto_protocol_equiv (x y : proto_Z5) : Prop :=
  exists n : Z,
    Z.sub (p5_a x) (p5_a y) = n /\
    Z.sub (p5_b x) (p5_b y) = Z.opp n /\
    p5_d x = p5_d y /\
    p5_alpha x = p5_alpha y /\
    p5_beta x = p5_beta y.

Definition proto_protocol_projection (x : proto_Z5) : proto_Z4 :=
  ProtoZ4 (Z.add (p5_a x) (p5_b x)) (p5_d x) (p5_alpha x) (p5_beta x).

Definition proto_protocol_section (y : proto_Z4) : proto_Z5 :=
  ProtoZ5 (p4_ab y) 0 (p4_d y) (p4_alpha y) (p4_beta y).

Theorem proto_protocol_equiv_is_equivalence :
  RelationClasses.Equivalence proto_protocol_equiv.
Proof.
  constructor.
  - intros [a b d la lb]. exists 0%Z. cbn. repeat split; lia.
  - intros [a b d la lb] [a' b' d' la' lb']
      [n [Ha [Hb [Hd [Hla Hlb]]]]].
    exists (- n)%Z. cbn in *. repeat split; lia.
  - intros [a b d la lb] [a' b' d' la' lb']
      [a'' b'' d'' la'' lb'']
      [n [Ha [Hb [Hd [Hla Hlb]]]]]
      [m [Ha' [Hb' [Hd' [Hla' Hlb']]]]].
    exists (n + m)%Z. cbn in *. repeat split; lia.
Qed.

Theorem prototype_protocol_Z4_quotient :
  (forall x y, proto_protocol_equiv x y ->
     proto_protocol_projection x = proto_protocol_projection y) /\
  (forall y, proto_protocol_projection (proto_protocol_section y) = y) /\
  (forall x, proto_protocol_equiv x
     (proto_protocol_section (proto_protocol_projection x))).
Proof.
  repeat split.
  - intros [a b d la lb] [a' b' d' la' lb']
      [n [Ha [Hb [Hd [Hla Hlb]]]]].
    cbn in *. assert (Hab : Z.add a b = Z.add a' b') by lia.
    subst d' la' lb'. unfold proto_protocol_projection. cbn. rewrite Hab. reflexivity.
  - intros [u d la lb]. unfold proto_protocol_projection, proto_protocol_section. cbn. f_equal; lia.
  - intros [a b d la lb]. exists (- b)%Z.
    cbn. repeat split; lia.
Qed.
Definition prototype_forest_parities : list bool := [false; true].
Definition gate_bool (F : list bool) : bool :=
  Nat.eqb (count_occ Bool.bool_dec F false) (count_occ Bool.bool_dec F true) &&
  Nat.ltb 0 (count_occ Bool.bool_dec F false).

Lemma prototype_gate_holds : gate_bool prototype_forest_parities = true.
Proof. reflexivity. Qed.
Lemma deleting_even_tree_breaks_gate : gate_bool [true] = false.
Proof. reflexivity. Qed.
Lemma deleting_odd_tree_breaks_gate : gate_bool [false] = false.
Proof. reflexivity. Qed.

Record proto_state : Type := ProtoState {
  proto_root_frame : s3;
  proto_alpha_active : bool;
  proto_beta_active : bool;
  proto_alpha_boundary : bool;
  proto_beta_boundary : bool;
  proto_alpha_count : nat;
  proto_beta_count : nat
}.

Definition proto_K0 : proto_state :=
  ProtoState S3e true true false false 0 0.

Definition attach_alpha (K : proto_state) : option proto_state :=
  if proto_alpha_active K then
    Some (ProtoState (s3_mul S3a01 (proto_root_frame K)) false
      (proto_beta_active K) true (proto_beta_boundary K)
      (S (proto_alpha_count K)) (proto_beta_count K))
  else None.

Definition attach_beta (K : proto_state) : option proto_state :=
  if proto_beta_active K then
    Some (ProtoState (s3_mul S3b12 (proto_root_frame K))
      (proto_alpha_active K) false (proto_alpha_boundary K) true
      (proto_alpha_count K) (S (proto_beta_count K)))
  else None.

Definition K_alpha_beta : proto_state :=
  ProtoState S3ba false false true true 1 1.
Definition K_beta_alpha : proto_state :=
  ProtoState S3ab false false true true 1 1.

Lemma alpha_then_beta_computes :
  exists K1, attach_alpha proto_K0 = Some K1 /\
    attach_beta K1 = Some K_alpha_beta.
Proof.
  exists (ProtoState S3a01 false true true false 1 0).
  split; reflexivity.
Qed.

Lemma beta_then_alpha_computes :
  exists K1, attach_beta proto_K0 = Some K1 /\
    attach_alpha K1 = Some K_beta_alpha.
Proof.
  exists (ProtoState S3b12 true false false true 0 1).
  split; reflexivity.
Qed.

Definition proto_base (K : proto_state) : (bool * bool)%type :=
  (proto_alpha_boundary K, proto_beta_boundary K).

(* theta sends either loop to 1, hence either attached loop kills Z2. *)
Definition proto_model_quotient (K : proto_state) : bool :=
  negb (orb (proto_alpha_boundary K) (proto_beta_boundary K)).

Definition proto_source_spectrum (K : proto_state) : nat * nat :=
  (proto_alpha_count K, proto_beta_count K).

Definition proto_form (K : proto_state) (r : s3) : Prop :=
  proto_root_frame K = r.
Definition proto_future (K : proto_state) (r : s3) (_ : nat) : Prop :=
  proto_form K r.

(* In the rigid, no-new-site fragment a source-preserving filler must preserve
   the two boundary fields, the source multiset, and the root frame. *)
Definition proto_filler (K L : proto_state) : Prop :=
  proto_base K = proto_base L /\
  proto_source_spectrum K = proto_source_spectrum L /\
  proto_root_frame K = proto_root_frame L.

Theorem prototype_same_base_model_instances_and_spectrum :
  proto_base K_alpha_beta = proto_base K_beta_alpha /\
  proto_model_quotient K_alpha_beta = proto_model_quotient K_beta_alpha /\
  proto_source_spectrum K_alpha_beta = proto_source_spectrum K_beta_alpha.
Proof. repeat split; reflexivity. Qed.

Theorem prototype_no_source_preserving_filler :
  ~ proto_filler K_alpha_beta K_beta_alpha.
Proof.
  intros [_ [_ Hframe]].
  discriminate Hframe.
Qed.

Definition prototype_curvature : s3 :=
  s3_mul (s3_mul S3b12 S3a01)
    (s3_inv (s3_mul S3a01 S3b12)).

Lemma prototype_curvature_is_nonidentity :
  prototype_curvature <> S3e.
Proof. discriminate. Qed.

Theorem rigid_filler_commutation_curvature_future_equivalence :
  (proto_filler K_alpha_beta K_beta_alpha <->
   s3_mul S3b12 S3a01 = s3_mul S3a01 S3b12) /\
  (s3_mul S3b12 S3a01 = s3_mul S3a01 S3b12 <->
   prototype_curvature = S3e) /\
  (proto_filler K_alpha_beta K_beta_alpha <->
   forall r n,
     proto_future K_alpha_beta r n <-> proto_future K_beta_alpha r n).
Proof.
  split.
  - split.
    + intro H. exfalso. apply prototype_no_source_preserving_filler. exact H.
    + intro H. exfalso. apply source_transpositions_do_not_commute. exact H.
  - split.
    + split.
      * intro H. exfalso. apply source_transpositions_do_not_commute. exact H.
      * intro H. exfalso. apply prototype_curvature_is_nonidentity. exact H.
    + split.
      * intros [_ [_ Hframe]] r n. unfold proto_future, proto_form.
        rewrite Hframe. reflexivity.
      * intro Hfuture.
        specialize (Hfuture S3ba 0).
        assert (Hleft : proto_future K_alpha_beta S3ba 0) by reflexivity.
        apply (proj1 Hfuture) in Hleft.
        discriminate Hleft.
Qed.
Definition r_star : s3 := S3ba.

Theorem prototype_different_formation :
  proto_form K_alpha_beta r_star /\
  ~ proto_form K_beta_alpha r_star.
Proof.
  split; cbn.
  - reflexivity.
  - discriminate.
Qed.

Theorem theorem_11_1_same_base_different_future :
  proto_base K_alpha_beta = proto_base K_beta_alpha /\
  proto_model_quotient K_alpha_beta = proto_model_quotient K_beta_alpha /\
  proto_source_spectrum K_alpha_beta = proto_source_spectrum K_beta_alpha /\
  ~ proto_filler K_alpha_beta K_beta_alpha /\
  exists r n, proto_future K_alpha_beta r n /\
              ~ proto_future K_beta_alpha r n.
Proof.
  repeat split; try reflexivity.
  - exact prototype_no_source_preserving_filler.
  - exists r_star, 0.
    exact prototype_different_formation.
Qed.

Definition square_available (has_alpha has_beta : bool) : bool :=
  andb has_alpha has_beta.

Lemma deleting_either_source_loop_removes_square :
  square_available false true = false /\
  square_available true false = false.
Proof. split; reflexivity. Qed.

Definition abelian_frame := (bool * bool)%type.
Definition abelian_mul (x y : abelian_frame) : abelian_frame :=
  (xorb (fst x) (fst y), xorb (snd x) (snd y)).
Definition abelian_alpha : abelian_frame := (true, false).
Definition abelian_beta : abelian_frame := (false, true).

Lemma abelianizing_makes_the_square_fillable :
  abelian_mul abelian_beta abelian_alpha =
  abelian_mul abelian_alpha abelian_beta.
Proof. reflexivity. Qed.

Definition future_without_FORM (_ : proto_state) (_ : s3) (_ : nat) : Prop :=
  False.

Lemma deleting_FORM_erases_future_difference :
  forall r n,
    future_without_FORM K_alpha_beta r n <->
    future_without_FORM K_beta_alpha r n.
Proof. intros r n; split; contradiction. Qed.

(* A closed, nonempty execution fragment: verified certificate, shared
   model, and assembly of a seed. *)
Inductive proto_phase := RawPhase | VerifiedPhase | ModelPhase | SeedPhase.
Inductive proto_step : proto_phase -> proto_phase -> Prop :=
| ProtoVerify : proto_step RawPhase VerifiedPhase
| ProtoAdmitModel : proto_step VerifiedPhase ModelPhase
| ProtoAssemble : proto_step ModelPhase SeedPhase.

Inductive proto_derivation : proto_phase -> proto_phase -> Prop :=
| ProtoDer_refl : forall p, proto_derivation p p
| ProtoDer_cons : forall p q r,
    proto_derivation p q -> proto_step q r -> proto_derivation p r.

Lemma prototype_has_a_nonempty_legal_derivation :
  proto_derivation RawPhase SeedPhase.
Proof.
  eapply ProtoDer_cons.
  - eapply ProtoDer_cons.
    + eapply ProtoDer_cons.
      * apply ProtoDer_refl.
      * apply ProtoVerify.
    + apply ProtoAdmitModel.
  - apply ProtoAssemble.
Qed.

Record finite_nontrivial_model : Type := FiniteNontrivialModel {
  model_carrier : list proto_state;
  model_gate : gate_bool prototype_forest_parities = true;
  model_reflection :
    z2_add (theta_z2 EdgeA) (theta_z2 EdgeB) = false;
  model_run : proto_derivation RawPhase SeedPhase;
  model_distinct_states : K_alpha_beta <> K_beta_alpha;
  model_same_base :
    proto_base K_alpha_beta = proto_base K_beta_alpha;
  model_distinct_formation :
    proto_form K_alpha_beta r_star /\ ~ proto_form K_beta_alpha r_star
}.

Definition PSCA_finite_model : finite_nontrivial_model.
Proof.
  refine (FiniteNontrivialModel [proto_K0; K_alpha_beta; K_beta_alpha]
    prototype_gate_holds prototype_reflection_respected
    prototype_has_a_nonempty_legal_derivation _ eq_refl
    prototype_different_formation).
  discriminate.
Defined.

Theorem PSCA_nontrivial : exists M : finite_nontrivial_model,
  proto_derivation RawPhase SeedPhase /\
  K_alpha_beta <> K_beta_alpha.
Proof.
  exists PSCA_finite_model.
  split.
  - exact (model_run PSCA_finite_model).
  - exact (model_distinct_states PSCA_finite_model).
Qed.

Section FlatNormalization.
  Context {State Base RuleName : Type}.
  Variable base_of : State -> Base.
  Variable state_form : State -> RuleName -> Prop.

  Record flat_normalization (Y : Type) : Type := FlatNormalization {
    flat_P : State -> Y;
    flat_Pbar : Base -> Y;
    flat_form : Y -> RuleName -> Prop;
    flat_factors : forall K, flat_P K = flat_Pbar (base_of K);
    flat_preserves_form : forall K r,
      state_form K r <-> flat_form (flat_P K) r
  }.

  Theorem equal_base_different_form_forbids_flat_normalization :
    forall K L r,
      base_of K = base_of L ->
      state_form K r -> ~ state_form L r ->
      forall (Y : Type), flat_normalization Y -> False.
  Proof.
    intros K L r Hbase HK HL Y FN.
    destruct FN as [P Pbar FY Hfactor Hform].
    apply HL.
    apply (proj2 (Hform L r)).
    rewrite Hfactor.
    rewrite <- Hbase.
    rewrite <- Hfactor.
    apply (proj1 (Hform K r)).
    exact HK.
  Qed.
End FlatNormalization.

Theorem theorem_12_1_no_flat_normalization :
  forall (Y : Type),
  @flat_normalization proto_state ((bool * bool)%type) s3
      proto_base proto_form Y -> False.
Proof.
  apply (@equal_base_different_form_forbids_flat_normalization
    proto_state ((bool * bool)%type) s3 proto_base proto_form
    K_alpha_beta K_beta_alpha r_star).
  - reflexivity.
  - exact (proj1 prototype_different_formation).
  - exact (proj2 prototype_different_formation).
Qed.

Record source_signature (S : Type) : Type := SourceSignature {
  state_rel : S -> nat -> Prop;
  attach_edge : S -> nat -> raw_path -> S -> Prop;
  source_site_rel : S -> nat -> source_kind -> nat -> option nat -> nat -> bool -> Prop;
  source_cell_rel : S -> nat -> nat -> nat -> list signed_source -> Prop;
  birth_rel : S -> nat -> nat -> Prop;
  fill_sq_rel : S -> nat -> raw_path -> nat -> raw_path -> nat -> Prop;
  curv_sq_rel : S -> nat -> raw_path -> nat -> raw_path -> nat -> nat -> Prop;
  state_form_rel : S -> nat -> Prop;
  qcomp_rel : S -> S -> S -> Prop;
  omega_rel : S -> list (signed_source * nat) -> Prop;
  source_extensional : forall x y,
    (forall v, state_rel x v <-> state_rel y v) ->
    (forall i k c a f b,
      source_site_rel x i k c a f b <->
      source_site_rel y i k c a f b) ->
    (forall j i h w,
      source_cell_rel x j i h w <-> source_cell_rel y j i h w) ->
    (forall i j, birth_rel x i j <-> birth_rel y i j) ->
    x = y
}.

Record fully_faithful_state_translation
    {S T : Type} (SS : source_signature S) (TS : source_signature T) : Type :=
  FullyFaithfulStateTranslation {
    translate_state : S -> T;
    ff_state_rel : forall x v,
      state_rel SS x v <-> state_rel TS (translate_state x) v;
    ff_attach : forall x s p y,
      attach_edge SS x s p y <->
      attach_edge TS (translate_state x) s p (translate_state y);
    ff_site : forall x i k c a f b,
      source_site_rel SS x i k c a f b <->
      source_site_rel TS (translate_state x) i k c a f b;
    ff_cell : forall x j i h w,
      source_cell_rel SS x j i h w <->
      source_cell_rel TS (translate_state x) j i h w;
    ff_birth : forall x i j,
      birth_rel SS x i j <-> birth_rel TS (translate_state x) i j;
    ff_fill : forall x s p t q phi,
      fill_sq_rel SS x s p t q phi <->
      fill_sq_rel TS (translate_state x) s p t q phi;
    ff_curv : forall x s p t q k d,
      curv_sq_rel SS x s p t q k d <->
      curv_sq_rel TS (translate_state x) s p t q k d;
    ff_form : forall x r,
      state_form_rel SS x r <-> state_form_rel TS (translate_state x) r;
    ff_qcomp : forall x y z,
      qcomp_rel SS x y z <->
      qcomp_rel TS (translate_state x) (translate_state y) (translate_state z);
    ff_omega : forall x w,
      omega_rel SS x w <-> omega_rel TS (translate_state x) w
  }.

Theorem fully_faithful_translation_is_injective :
  forall S T (SS : source_signature S) (TS : source_signature T)
    (F : fully_faithful_state_translation SS TS) x y,
    translate_state F x = translate_state F y -> x = y.
Proof.
  intros S T SS TS F x y Heq.
  apply (source_extensional SS x y).
  - intro v.
    rewrite (ff_state_rel F x v), (ff_state_rel F y v), Heq.
    reflexivity.
  - intros i k c a f b.
    rewrite (ff_site F x i k c a f b), (ff_site F y i k c a f b), Heq.
    reflexivity.
  - intros j i h w.
    rewrite (ff_cell F x j i h w), (ff_cell F y j i h w), Heq.
    reflexivity.
  - intros i j.
    rewrite (ff_birth F x i j), (ff_birth F y i j), Heq.
    reflexivity.
Qed.

Inductive reconstructed_object (S : Type) : Type :=
| Reconstructed (source : S).

Definition reconstruct {S} (x : S) : reconstructed_object S :=
  Reconstructed x.
Definition decode_reconstruction {S} (x : reconstructed_object S) : S :=
  match x with Reconstructed y => y end.

Lemma reconstruction_left_inverse : forall S (x : S),
  decode_reconstruction (reconstruct x) = x.
Proof. reflexivity. Qed.

Lemma reconstruction_right_inverse : forall S (x : reconstructed_object S),
  reconstruct (decode_reconstruction x) = x.
Proof. intros S [x]; reflexivity. Qed.

Record groupoid_iso (A B : Type) : Type := GroupoidIso {
  iso_to : A -> B;
  iso_from : B -> A;
  iso_from_to : forall x, iso_from (iso_to x) = x;
  iso_to_from : forall y, iso_to (iso_from y) = y
}.

Theorem reconstructed_objects_bijective :
  forall S, groupoid_iso S (reconstructed_object S).
Proof.
  intro S.
  refine (GroupoidIso reconstruct decode_reconstruction _ _).
  - apply reconstruction_left_inverse.
  - apply reconstruction_right_inverse.
Defined.

Record source_groupoid (O : Type) : Type := SourceGroupoid {
  sg_filler : O -> O -> nat -> Prop;
  sg_id_code : O -> nat;
  sg_id_filler : forall x, sg_filler x x (sg_id_code x);
  sg_inverse_code : nat -> nat;
  sg_inverse_filler : forall x y phi,
    sg_filler x y phi -> sg_filler y x (sg_inverse_code phi);
  sg_comp_code : nat -> nat -> nat;
  sg_comp_filler : forall x y z phi psi,
    sg_filler x y phi -> sg_filler y z psi ->
    sg_filler x z (sg_comp_code psi phi);
  sg_holonomy : O -> nat;
  sg_spectrum : O -> list (signed_source * nat);
  sg_future : O -> nat -> Prop;
  sg_filler_preserves_holonomy : forall x y phi,
    sg_filler x y phi -> sg_holonomy x = sg_holonomy y;
  sg_filler_preserves_spectrum : forall x y phi,
    sg_filler x y phi -> sg_spectrum x = sg_spectrum y;
  sg_filler_preserves_future : forall x y phi r,
    sg_filler x y phi -> (sg_future x r <-> sg_future y r)
}.

Definition reconstructed_groupoid {O} (G : source_groupoid O) :
    source_groupoid (reconstructed_object O).
Proof.
  refine {| sg_filler := fun x y phi =>
              sg_filler G (decode_reconstruction x)
                (decode_reconstruction y) phi;
            sg_id_code := fun x => sg_id_code G (decode_reconstruction x);
            sg_inverse_code := sg_inverse_code G;
            sg_comp_code := sg_comp_code G;
            sg_holonomy := fun x => sg_holonomy G (decode_reconstruction x);
            sg_spectrum := fun x => sg_spectrum G (decode_reconstruction x);
            sg_future := fun x => sg_future G (decode_reconstruction x) |}.
  - intro x. apply sg_id_filler.
  - intros x y phi H. apply sg_inverse_filler. exact H.
  - intros x y z phi psi Hphi Hpsi.
    eapply sg_comp_filler; eauto.
  - intros x y phi H. eapply sg_filler_preserves_holonomy; eauto.
  - intros x y phi H. eapply sg_filler_preserves_spectrum; eauto.
  - intros x y phi r H. eapply sg_filler_preserves_future; eauto.
Defined.

Record source_groupoid_iso {O O' : Type}
    (G : source_groupoid O) (H : source_groupoid O') : Type :=
  SourceGroupoidIso {
    sgi_objects : groupoid_iso O O';
    sgi_filler : forall x y phi,
      sg_filler G x y phi <->
      sg_filler H (iso_to sgi_objects x) (iso_to sgi_objects y) phi;
    sgi_holonomy : forall x,
      sg_holonomy G x = sg_holonomy H (iso_to sgi_objects x);
    sgi_spectrum : forall x,
      sg_spectrum G x = sg_spectrum H (iso_to sgi_objects x);
    sgi_future : forall x r,
      sg_future G x r <-> sg_future H (iso_to sgi_objects x) r
  }.

Theorem theorem_12_2_source_groupoid_reconstruction :
  forall O (G : source_groupoid O),
    source_groupoid_iso G (reconstructed_groupoid G).
Proof.
  intros O G.
  refine {| sgi_objects := reconstructed_objects_bijective O |}.
  - intros x y phi. reflexivity.
  - intro x. reflexivity.
  - intro x. reflexivity.
  - intros x r. reflexivity.
Defined.
Corollary theorem_12_3_no_same_base_collapse :
  forall S T (SS : source_signature S) (TS : source_signature T)
    (F : fully_faithful_state_translation SS TS) x y,
    x <> y -> translate_state F x <> translate_state F y.
Proof.
  intros S T SS TS F x y Hneq Heq.
  apply Hneq.
  eapply fully_faithful_translation_is_injective.
  exact Heq.
Qed.


Corollary theorem_12_3_general_structure_noneliminability :
  forall S T (SS : source_signature S) (TS : source_signature T)
    (F : fully_faithful_state_translation SS TS) x y,
    x <> y ->
    translate_state F x <> translate_state F y /\
    ~ (forall z, translate_state F z = translate_state F x).
Proof.
  intros S T SS TS F x y Hneq.
  split.
  - eapply theorem_12_3_no_same_base_collapse. exact Hneq.
  - intro Hone.
    apply Hneq.
    eapply fully_faithful_translation_is_injective.
    symmetry. apply Hone.
Qed.
Theorem finite_model_establishes_relative_consistency_and_nontriviality :
  proto_derivation RawPhase SeedPhase /\
  exists K L, proto_base K = proto_base L /\ K <> L.
Proof.
  split.
  - exact prototype_has_a_nonempty_legal_derivation.
  - exists K_alpha_beta, K_beta_alpha.
    split.
    + reflexivity.
    + discriminate.
Qed.


(* ================================================================= *)
(* Inlined verbatim from PSCA2170_Meta.v; only internal PSCA Require removed. *)
(* ================================================================= *)
(* PSCA 2.3, sections 13--14: effective no-go theorem and package. *)
From Stdlib Require Import List Bool Arith PeanoNat.
Import ListNotations.
Set Implicit Arguments.

(*
  Explicit interface for the standard acceptable program numbering fixed in
  source section 2.  It contains only the usual closure/undecidability
  metatheory used in section 13; it is not an axiom in the executable PSCA
  kernel or finite model.
*)
Record effective_metatheory : Type := EffectiveMetatheory {
  em_phi : nat -> nat -> nat -> Prop;
  em_RE1 : (nat -> Prop) -> Prop;
  em_RE2 : (nat -> nat -> Prop) -> Prop;
  em_Recursive1 : (nat -> nat) -> Prop;
  em_Recursive2 : (nat -> nat -> nat) -> Prop;

  em_RE2_ext : forall P Q,
    (forall x y, P x y <-> Q x y) -> em_RE2 P -> em_RE2 Q;
  em_halt_RE : em_RE2 (fun e x => exists v, em_phi e x v);
  em_RE_preimage2 : forall R f g,
    em_RE2 R -> em_Recursive2 f -> em_Recursive2 g ->
    em_RE2 (fun x y => R (f x y) (g x y));
  em_RE_projection : forall R,
    em_RE2 R -> em_RE1 (fun y => exists x, R x y);
  em_RE1_preimage2 : forall P f,
    em_RE1 P -> em_Recursive2 f ->
    em_RE2 (fun x y => P (f x y));

  em_recursive_comp11 : forall f g,
    em_Recursive1 f -> em_Recursive1 g ->
    em_Recursive1 (fun x => f (g x));
  em_recursive_pair : forall f g h,
    em_Recursive2 f -> em_Recursive1 g -> em_Recursive1 h ->
    em_Recursive2 (fun x y => f (g x) (h y));
  em_recursive_left : forall f,
    em_Recursive1 f -> em_Recursive2 (fun x _ => f x);
  em_const_recursive : forall n,
    em_Recursive1 (fun _ => n);

  em_RE_both_sides_decidable : forall P,
    em_RE2 P -> em_RE2 (fun x y => ~ P x y) ->
    forall x y, {P x y} + {~ P x y};
  em_halting_undecidable :
    (forall e x, {exists v, em_phi e x v} +
                 {~ exists v, em_phi e x v}) -> False;

  em_nowhere : nat;
  em_nowhere_spec : forall x v, ~ em_phi em_nowhere x v;
  em_specialize : nat -> nat -> nat;
  em_specialize_recursive : em_Recursive2 em_specialize;
  em_specialize_zero : forall e x,
    (forall u v,
      em_phi (em_specialize e x) u v <-> em_phi em_nowhere u v) <->
    ~ exists v, em_phi e x v
}.

Definition program_equiv (E : effective_metatheory) (e f : nat) : Prop :=
  forall x v, em_phi E e x v <-> em_phi E f x v.

Theorem program_equivalence_is_not_RE :
  forall E, ~ em_RE2 E (program_equiv E).
Proof.
  intros E HequivRE.
  assert (Hconst1 : em_Recursive1 E (fun _ => em_nowhere E)).
  - apply em_const_recursive.
  - assert (Hconst2 : em_Recursive2 E (fun _ _ => em_nowhere E)).
    + apply em_recursive_left.
      exact Hconst1.
    + pose proof (em_RE_preimage2 E
        (program_equiv E) (em_specialize E)
        (fun _ _ => em_nowhere E)
        HequivRE (em_specialize_recursive E) Hconst2) as Hpre.
      assert (Hnonhalt :
        em_RE2 E (fun e x => ~ exists v, em_phi E e x v)).
      * eapply em_RE2_ext.
        -- intros e x.
           apply em_specialize_zero.
        -- exact Hpre.
      * apply (em_halting_undecidable E).
        apply (em_RE_both_sides_decidable E
          (fun e x => exists v, em_phi E e x v)).
        -- exact (em_halt_RE E).
        -- exact Hnonhalt.
Qed.

(*
  All finite tuples below are represented by their fixed natural-number code.
  Thus every displayed higher-arity source constructor becomes a binary
  function (formula code, tuple-payload code), without losing a coordinate.
*)
Record static_target (E : effective_metatheory) : Type := StaticTarget {
  st_formb : nat -> bool;
  st_event_formula : nat -> nat -> nat;
  st_pcomp_formula : nat -> nat -> nat;
  st_state_rel_formula : nat -> nat -> nat;
  st_attach_formula : nat -> nat -> nat;
  st_source_inc_formula : nat -> nat -> nat;
  st_fill_formula : nat -> nat -> nat;
  st_curv_formula : nat -> nat -> nat;
  st_state_form_formula : nat -> nat -> nat;
  st_qcomp_formula : nat -> nat -> nat;
  st_eq_formula : nat -> nat -> nat;

  st_form_recursive : em_Recursive1 E (fun n => if st_formb n then 1 else 0);
  st_event_recursive : em_Recursive2 E st_event_formula;
  st_pcomp_recursive : em_Recursive2 E st_pcomp_formula;
  st_state_rel_recursive : em_Recursive2 E st_state_rel_formula;
  st_attach_recursive : em_Recursive2 E st_attach_formula;
  st_source_inc_recursive : em_Recursive2 E st_source_inc_formula;
  st_fill_recursive : em_Recursive2 E st_fill_formula;
  st_curv_recursive : em_Recursive2 E st_curv_formula;
  st_state_form_recursive : em_Recursive2 E st_state_form_formula;
  st_qcomp_recursive : em_Recursive2 E st_qcomp_formula;
  st_eq_recursive : em_Recursive2 E st_eq_formula;

  (* Conservative totalization: on every well-formed leading formula, each
     constructor returns a formula even for natural payloads outside the
     intended typed coding domain.  Hence the source typing laws hold on the
     intended domain without introducing partial operations. *)
  st_event_closed : forall A z,
      st_formb A = true -> st_formb (st_event_formula A z) = true;
  st_pcomp_closed : forall A z,
      st_formb A = true -> st_formb (st_pcomp_formula A z) = true;
  st_state_rel_closed : forall A z,
      st_formb A = true -> st_formb (st_state_rel_formula A z) = true;
  st_attach_closed : forall A z,
      st_formb A = true -> st_formb (st_attach_formula A z) = true;
  st_source_inc_closed : forall A z,
      st_formb A = true -> st_formb (st_source_inc_formula A z) = true;
  st_fill_closed : forall A z,
      st_formb A = true -> st_formb (st_fill_formula A z) = true;
  st_curv_closed : forall A z,
      st_formb A = true -> st_formb (st_curv_formula A z) = true;
  st_state_form_closed : forall A z,
      st_formb A = true -> st_formb (st_state_form_formula A z) = true;
  st_qcomp_closed : forall A z,
      st_formb A = true -> st_formb (st_qcomp_formula A z) = true;
  st_eq_closed : forall A B,
      st_formb A = true -> st_formb B = true ->
      st_formb (st_eq_formula A B) = true;

  st_prf : nat -> nat -> Prop;
  st_prf_RE : em_RE2 E st_prf;
  st_prf_wf : forall pi A, st_prf pi A -> st_formb A = true
}.

Definition target_provable {E} (L : static_target E) (A : nat) : Prop :=
  exists pi, st_prf L pi A.

Record source_public_signature (E : effective_metatheory) : Type :=
  SourcePublicSignature {
    sp_event : nat -> nat -> Prop;
    sp_pcomp : nat -> nat -> Prop;
    sp_state_rel : nat -> nat -> Prop;
    sp_attach : nat -> nat -> Prop;
    sp_source_inc : nat -> nat -> Prop;
    sp_fill : nat -> nat -> Prop;
    sp_curv : nat -> nat -> Prop;
    sp_state_form : nat -> nat -> Prop;
    sp_qcomp : nat -> nat -> Prop;
    sp_obseq : nat -> nat -> Prop;
    sp_J : nat -> nat;
    sp_J_recursive : em_Recursive1 E sp_J;
    sp_J_characterizes_programs : forall e f,
      sp_obseq (sp_J e) (sp_J f) <-> program_equiv E e f
  }.

Record qualified_encoding (E : effective_metatheory)
    (S : source_public_signature E) (L : static_target E) : Type :=
  QualifiedEncoding {
    qe_assembly : nat -> nat;
    qe_state : nat -> nat;
    qe_assembly_recursive : em_Recursive1 E qe_assembly;
    qe_state_recursive : em_Recursive1 E qe_state;

    qe_event_iff : forall a ev,
      sp_event S a ev <->
      target_provable L (st_event_formula L (qe_assembly a) ev);
    qe_pcomp_iff : forall triple payload,
      sp_pcomp S triple payload <->
      target_provable L (st_pcomp_formula L (qe_assembly triple) payload);
    qe_state_rel_iff : forall s payload,
      sp_state_rel S s payload <->
      target_provable L (st_state_rel_formula L (qe_state s) payload);
    qe_attach_iff : forall s payload,
      sp_attach S s payload <->
      target_provable L (st_attach_formula L (qe_state s) payload);
    qe_source_inc_iff : forall s payload,
      sp_source_inc S s payload <->
      target_provable L (st_source_inc_formula L (qe_state s) payload);
    qe_fill_iff : forall s payload,
      sp_fill S s payload <->
      target_provable L (st_fill_formula L (qe_state s) payload);
    qe_curv_iff : forall s payload,
      sp_curv S s payload <->
      target_provable L (st_curv_formula L (qe_state s) payload);
    qe_state_form_iff : forall s payload,
      sp_state_form S s payload <->
      target_provable L (st_state_form_formula L (qe_state s) payload);
    qe_qcomp_iff : forall s payload,
      sp_qcomp S s payload <->
      target_provable L (st_qcomp_formula L (qe_state s) payload);

    qe_full_abstraction : forall a b,
      sp_obseq S a b <->
      target_provable L
        (st_eq_formula L (qe_assembly a) (qe_assembly b))
  }.

Definition J_query {E S L}
    (Q : @qualified_encoding E S L) (e f : nat) : nat :=
  st_eq_formula L
    (qe_assembly Q (sp_J S e))
    (qe_assembly Q (sp_J S f)).

Lemma J_query_recursive :
  forall E S L (Q : @qualified_encoding E S L),
    em_Recursive2 E (J_query Q).
Proof.
  intros E S L Q.
  unfold J_query.
  apply em_recursive_pair.
  - exact (st_eq_recursive L).
  - apply em_recursive_comp11.
    + exact (qe_assembly_recursive Q).
    + exact (sp_J_recursive S).
  - apply em_recursive_comp11.
    + exact (qe_assembly_recursive Q).
    + exact (sp_J_recursive S).
Qed.

Theorem theorem_13_1_no_effective_fully_abstract_encoding :
  forall E (S : source_public_signature E) (L : static_target E),
    @qualified_encoding E S L -> False.
Proof.
  intros E S L Q.
  apply (program_equivalence_is_not_RE E).
  assert (Hprov : em_RE1 E (target_provable L)).
  - apply em_RE_projection.
    exact (st_prf_RE L).
  - assert (Hqueries :
      em_RE2 E (fun e f => target_provable L (J_query Q e f))).
    + apply em_RE1_preimage2.
      * exact Hprov.
      * apply J_query_recursive.
    + eapply em_RE2_ext.
      * intros e f.
        unfold J_query.
        rewrite <- (qe_full_abstraction Q (sp_J S e) (sp_J S f)).
        apply sp_J_characterizes_programs.
      * exact Hqueries.
Qed.

(*
  Section 14 package.  A packaged kernel must carry a transition witness
  indexed by that very kernel; an unrelated prototype model is not enough.
*)
Record KernelTransitionModel (P : psca_kernel) : Type := {
  transition_source : context;
  transition_operation : op;
  transition_target : context;
  transition_trace : list token;
  transition_rule :
    Rule P transition_source transition_operation
      transition_target transition_trace;
  transition_nonidentity : transition_source <> transition_target
}.

Record PSCA_2_3 : Type := PSCA23 {
  system_kernel : psca_kernel;
  system_rule : context -> op -> context -> list token -> Prop;
  system_rule_exact : system_rule = Rule system_kernel;
  system_derivation :
    context -> list (op * list token) -> context -> Prop;
  system_derivation_exact : system_derivation = Der system_kernel;
  system_event : assembly system_kernel -> event -> Prop;
  system_event_exact : system_event = event_holds;
  system_transition_model : KernelTransitionModel system_kernel
}.

Definition package_PSCA_2_3
    (P : psca_kernel) (M : KernelTransitionModel P) : PSCA_2_3 :=
  {| system_kernel := P;
     system_rule := Rule P;
     system_rule_exact := eq_refl;
     system_derivation := Der P;
     system_derivation_exact := eq_refl;
     system_event := event_holds;
     system_event_exact := eq_refl;
     system_transition_model := M |}.

Definition string_has_semantics (P : psca_kernel) (w : word) : Prop :=
  exists c M K G0 G1 tr,
    cert_word c = w /\ SemCert (pk_generator P) c /\ pk_qual P c M /\
    pk_initial P c = Some K /\ Der P G0 tr G1 /\
    exists A : assembly P,
      asm_certificate A = c /\ asm_model A = M.


(* ================================================================= *)
(* Inlined verbatim from PSCA2170_Model.v; only internal PSCA Require removed. *)
(* ================================================================= *)
(* A closed finite witness for one explicitly constructed PSCA kernel. *)
From Stdlib Require Import List Bool Arith PeanoNat Relations.
Import ListNotations.
Set Implicit Arguments.

Definition finite_generator : generator_data.
Proof.
  refine {|
    cfg_ok := fun _ => True;
    init_cfg := fun _ => 0;
    step_g := fun _ _ _ => False;
    halt_tree_g := fun _ _ => False;
    tree_g := fun _ => False;
    comp_run_g := fun _ _ _ => False;
    trace_g := fun _ _ _ _ => False;
    phi_g := fun _ _ _ => False;
    prefix_trace_g := fun _ _ _ => False;
    emit_g := fun a b => [a; b];
    nat_word_g := fun n => [n];
    prf_h := fun _ _ => False;
    coverage_code := fun _ _ => 0;
    verifier := fun _ => false;
    nu_g := fun n => n
  |}.
  - intros e u v. split.
    + intro H. contradiction.
    + intros [r H]. contradiction.
  - intros a b c d H.
    injection H as Ha Hb.
    split; assumption.
  - intros w F pi Hfalse. contradiction.
  - intro c. split.
    + discriminate.
    + intros [_ [_ [_ [_ Hfalse]]]]. contradiction.
  - intros x y H. exact H.
  - intro t. reflexivity.
Defined.

Definition finite_unit_group : finite_group.
Proof.
  refine {|
    fg_carrier := [0];
    fg_e := 0;
    fg_mul := fun _ _ => 0;
    fg_inv := fun _ => 0
  |}.
  - intros x y _ _. simpl. auto.
  - intros x _. simpl. auto.
  - intros x y z _ _ _. reflexivity.
  - intros x H. simpl in H. destruct H as [-> | []]. reflexivity.
  - intros x H. simpl in H. destruct H as [-> | []]. reflexivity.
  - intros x H. simpl in H. destruct H as [-> | []]. reflexivity.
  - intros x H. simpl in H. destruct H as [-> | []]. reflexivity.
Defined.

Definition finite_kind (n : nat) : option source_kind :=
  match n with 0 => Some Monitor | S _ => None end.
Definition finite_color (n : nat) : option nat :=
  match n with 0 => Some 0 | S _ => None end.
Definition finite_frame (n : nat) : option nat :=
  match n with 0 => Some 0 | S _ => None end.
Definition finite_active (n : nat) : option bool :=
  match n with 0 => Some true | S _ => None end.

Definition finite_source_complex : source_complex :=
  SourceComplex 0 [0] [] [0] 0
    finite_kind finite_color (fun _ => None) finite_frame finite_active
    (fun _ => None) (fun _ => None) (fun _ => None) (fun _ => None).

Lemma finite_incidence_empty : forall x y,
  ~ incidence finite_source_complex x y.
Proof.
  intros x y H.
  destruct H as [[_ [Hcell _]] | [Hcell _]]; simpl in Hcell; contradiction.
Qed.

Lemma finite_incidence_acyclic :
  acyclic (incidence finite_source_complex).
Proof.
  intros x Hcycle.
  induction Hcycle.
  - exact (@finite_incidence_empty _ _ H).
  - exact IHHcycle1.
Qed.

Lemma finite_source_complex_wf : SourceCxWF finite_source_complex.
Proof.
  unfold SourceCxWF.
  repeat split.
  - constructor.
    + simpl; congruence.
    + constructor.
  - constructor.
  - intros x _ H. exact H.
  - simpl; auto.
  - intros z Hz. simpl in Hz. destruct Hz as [<- | []].
    exists Monitor. reflexivity.
  - intros z Hz. simpl in Hz. destruct Hz as [<- | []].
    exists 0. reflexivity.
  - intros z Hz. simpl in Hz. destruct Hz as [<- | []].
    exists 0. reflexivity.
  - intros z Hz. simpl in Hz. destruct Hz as [<- | []].
    exists true. reflexivity.
  - intros site Hsite Hslot.
    simpl in Hsite. destruct Hsite as [<- | []]. discriminate Hslot.
  - cbn in *; congruence.
  - cbn in *; congruence.
  - intros cell Hcell. cbn in Hcell. contradiction.
  - intros cell Hcell. cbn in Hcell. contradiction.
  - intros cell Hcell. cbn in Hcell. contradiction.
  - intros cell1 cell2 site Hatt _. discriminate Hatt.
  - cbn in *; congruence.
  - cbn in *; congruence.
  - cbn in *; congruence.
  - intros site Hsite Hnew.
    simpl in Hsite. destruct Hsite as [<- | []].
    exfalso. apply Hnew. simpl; auto.
  - exact finite_incidence_acyclic.
  - simpl in H. destruct H as [<- | []]. discriminate H0.
  - simpl in H. destruct H as [<- | []]. discriminate H0.
Qed.

Definition concrete_finite_kernel : psca_kernel.
Proof.
  refine {|
    pk_generator := finite_generator;
    pk_group := finite_unit_group;
    pk_source_value := fun _ => 0;
    pk_gen := fun _ _ _ => [];
    pk_source_word := fun _ => [];
    pk_rho := fun _ => 0;
    pk_first_nonbottom := fun _ => None;
    pk_path_ok := fun _ _ => True;
    pk_path_chain := fun _ _ => 0;
    pk_chain_add := fun _ x y => if Nat.eqb x y then 0 else 1;
    pk_chain_neg := fun _ x => x;
    pk_reflect2 := fun _ _ => True;
    pk_eta := fun _ x => x;
    pk_B2 := fun _ x => x = 0;
    pk_eta_rep := fun _ a => a;
    pk_path_id := fun t => RawPath t t [];
    pk_path_comp := fun p q => RawPath (path_start p) (path_finish q) [];
    pk_path_inv := fun p => RawPath (path_finish p) (path_start p) [];
    pk_can := fun _ => finite_source_complex;
    pk_initial := fun _ => None;
    pk_attach := fun _ _ _ _ => None;
    pk_N := fun _ _ => 0;
    pk_subgroup_member := fun _ _ => True;
    pk_subgroup_add := fun _ _ => 0;
    pk_cyclic_subgroup := fun _ => 0;
    pk_B := fun _ _ _ => True;
    pk_state_eta := fun _ _ _ => 0;
    pk_quotient := fun _ _ v => v;
    pk_Omega := fun _ => [];
    pk_parikh := fun _ => [];
    pk_spectrum_add := fun xs ys => xs ++ ys;
    pk_filler_table := fun _ _ _ _ _ phi => phi = 0;
    pk_filler := fun _ _ _ _ _ => True;
    pk_nofill_check := fun _ _ _ _ _ _ => false;
    pk_curv := fun _ _ _ => 0;
    pk_model_ok := fun _ _ => False;
    pk_qual := fun _ _ => False;
    pk_instance := fun _ _ _ _ _ => False;
    pk_transport := fun _ _ _ _ x => Some x;
    pk_model_quotient := fun _ _ _ => 0;
    pk_form := fun K u => sc_frame K (sc_root K) = Some u;
    pk_seed := fun u n => [u; n];
    pk_relation_witness := fun _ _ _ _ => False;
    pk_square_ready := fun _ _ _ _ _ => False;
    pk_compare := fun _ _ _ _ _ => inl 0
  |}.
  - intro s. reflexivity.
  - intro t. reflexivity.
  - intros c a. reflexivity.
  - intros c x y. cbn.
    destruct (Nat.eqb x y) eqn:Eeq.
    + apply Nat.eqb_eq in Eeq. subst. tauto.
    + apply Nat.eqb_neq in Eeq. split.
      * intro Heq. contradiction.
      * discriminate.
  - intros c t. cbn. tauto.
  - intros c p q Hp Hq Hend. cbn. tauto.
  - intros c p Hp. cbn. tauto.
  - intros c p p' q q' Hpp Hqq.
    unfold coded_path_equiv in *. cbn in *. tauto.
  - intros c p q r. unfold coded_path_equiv. cbn. tauto.
  - intros c p. unfold coded_path_equiv. cbn. tauto.
  - intros c p. unfold coded_path_equiv. cbn. tauto.
  - intros c p. unfold coded_path_equiv. cbn. tauto.
  - intros c p. unfold coded_path_equiv. cbn. tauto.  - intros K _. exact finite_source_complex_wf.
  - intro K. reflexivity.
  - intros K L HK HL _ _ _.
    transitivity finite_source_complex.
    + symmetry. exact HK.
    + exact HL.
  - intros c K H. discriminate.
  - intros c K sigma p K' H. discriminate.
  - intros c K sigma p K' H. discriminate.
  - intros c K v. tauto.
  - intros c K sigma p K' H. discriminate.
  - intros K K' K'' v. reflexivity.
  - intros c K sigma p K' H. discriminate.
  - intros K s p t q. split.
    + intro Hfill. exists 0. reflexivity.
    + intro Htable. exact I.
  - intros K s p t q. left. exists 0. reflexivity.
  - intros K s p t q phi d _ H. discriminate.
  - intros K p q. reflexivity.
  - intros c M H. contradiction.
  - intros c M K s p t q Kpq Kqp H. discriminate.
  - intros K u. reflexivity.
  - intros u n. reflexivity.
  - intros K s p t q H. contradiction.
  - intros K s p t q. reflexivity.
Defined.

Theorem concrete_finite_kernel_exists :
  inhabited psca_kernel.
Proof.
  exact (inhabits concrete_finite_kernel).
Qed.

Definition finite_cx_token : token :=
  Token 0 (CxTokP
    (ForestCertificate [] [] [] 0) finite_source_complex).
Definition finite_nonce : token := Token 1 (NonceP 0).
Definition finite_path_token : token :=
  Token 2 (PathTokP
    (ForestCertificate [] [] [] 0) finite_source_complex
    (RawPath 0 0 []) 0 0).

Definition finite_rule_context : context :=
  Context [] [finite_cx_token] [finite_nonce].
Definition finite_rule_context' : context :=
  Context (parent_edges ([finite_nonce] ++ [finite_cx_token]) [finite_path_token])
    [finite_cx_token] [finite_path_token].

Lemma finite_history_edge : forall x y,
  In (x, y) (parent_edges
    ([finite_nonce] ++ [finite_cx_token]) [finite_path_token]) ->
  y = 2 /\ (x = 1 \/ x = 0).
Proof.
  intros x y H. cbn in H.
  destruct H as [H | [H | []]]; inversion H; subst; auto.
Qed.

Lemma finite_history_path : forall x y,
  clos_trans nat
    (fun a b => In (a, b)
      (parent_edges ([finite_nonce] ++ [finite_cx_token]) [finite_path_token]))
    x y ->
  y = 2 /\ x <> 2.
Proof.
  intros x y H.
  induction H.
  - apply finite_history_edge in H.
    destruct H as [Hy [Hx | Hx]]; subst; split; congruence.
  - destruct IHclos_trans1 as [Hy Hx].
    destruct IHclos_trans2 as [_ Hyne].
    subst y. contradiction.
Qed.

Lemma finite_history_acyclic :
  acyclic (fun a b =>
    In (a, b)
      (parent_edges ([finite_nonce] ++ [finite_cx_token]) [finite_path_token])).
Proof.
  intros x H.
  apply finite_history_path in H.
  tauto.
Qed.

Lemma finite_rule_context_wf : ContextWF finite_rule_context.
Proof.
  unfold ContextWF, finite_rule_context, ids.
  cbn.
  split.
  - constructor.
    + intro Hdup. simpl in Hdup. destruct Hdup as [Hdup | []]. discriminate Hdup.
    + constructor.
      * simpl; tauto.
      * constructor.
  - split.
    + intros t H. destruct H as [<- | []]. exact I.
    + split.
      * intros t H. destruct H as [<- | []]. simpl. tauto.
      * split.
        -- intros t Hp Hl.
           destruct Hp as [<- | []].
           destruct Hl as [H | []]. discriminate H.
        -- intros x H. induction H; simpl in *; tauto.
Qed.

Lemma finite_rule_context'_wf : ContextWF finite_rule_context'.
Proof.
  unfold ContextWF, finite_rule_context', ids.
  cbn.
  split.
  - constructor.
    + intro Hdup. simpl in Hdup. destruct Hdup as [Hdup | []]. discriminate Hdup.
    + constructor.
      * simpl; tauto.
      * constructor.
  - split.
    + intros t H. destruct H as [<- | []]. exact I.
    + split.
      * intros t H. destruct H as [<- | []]. simpl. tauto.
      * split.
        -- intros t Hp Hl.
           destruct Hp as [<- | []].
           destruct Hl as [H | []]. discriminate H.
        -- exact finite_history_acyclic.
Qed.

Lemma finite_issue_update :
  context_update finite_rule_context finite_rule_context'
    [finite_nonce] [finite_cx_token] [finite_path_token].
Proof.
  unfold context_update.
  split.
  - exact finite_rule_context_wf.
  - split.
    + exact finite_rule_context'_wf.
    + split.
      * intros t H. simpl in H. destruct H as [<- | []].
        simpl. auto.
      * split.
        -- intros t H. simpl in H. destruct H as [<- | []].
           simpl. auto.
        -- split.
           ++ constructor.
              ** simpl; tauto.
              ** constructor.
           ++ split.
              ** intros o H. simpl in H. destruct H as [<- | []].
                 simpl. intros [Hid | [Hid | []]]; discriminate Hid.
              ** split.
                 --- unfold same_members. intro t. simpl. tauto.
                 --- split.
                     +++ intro t. simpl. split.
                         *** intros [Ht | []]. subst t. right. split; [left; reflexivity | simpl; tauto].
                         *** intros [[Ht Hnot] | [Ht _]].
                             { exfalso. apply Hnot. exact Ht. }
                             { destruct Ht as [Ht | []]. left. exact Ht. }
                     +++ unfold same_members. intro edge. simpl. tauto.
Qed.

Theorem complete_kernel_has_a_genuine_rule_step :
  Rule concrete_finite_kernel finite_rule_context ISSUE_PATH
    finite_rule_context' [finite_path_token].
Proof.
  eapply Rule_ISSUE.
  - simpl. auto.
  - reflexivity.
  - simpl. auto.
  - reflexivity.
  - exact I.
  - reflexivity.
  - reflexivity.
  - exact finite_issue_update.
Qed.

Lemma finite_rule_context_distinct :
  finite_rule_context <> finite_rule_context'.
Proof.
  intro Heq.
  injection Heq as _ Hlinear.
  discriminate Hlinear.
Qed.

Definition concrete_kernel_transition_model :
    KernelTransitionModel concrete_finite_kernel := {|
  transition_source := finite_rule_context;
  transition_operation := ISSUE_PATH;
  transition_target := finite_rule_context';
  transition_trace := [finite_path_token];
  transition_rule := complete_kernel_has_a_genuine_rule_step;
  transition_nonidentity := finite_rule_context_distinct
|}.

Definition concrete_PSCA_2_3 : PSCA_2_3 :=
  package_PSCA_2_3 concrete_kernel_transition_model.

Theorem concrete_PSCA_has_nontrivial_transition_model :
  exists M : KernelTransitionModel concrete_finite_kernel,
    transition_source M <>
    transition_target M.
Proof.
  exists concrete_kernel_transition_model.
  exact (transition_nonidentity
    concrete_kernel_transition_model).
Qed.

Print Assumptions concrete_finite_kernel_exists.
Print Assumptions complete_kernel_has_a_genuine_rule_step.
Print Assumptions concrete_PSCA_has_nontrivial_transition_model.


(* ================================================================= *)
(* Inlined verbatim from PSCA2170.v; only internal PSCA Require removed. *)
(* ================================================================= *)
(* Single checked entry point for PSCA 2.3 / note 2170. *)
Definition PSCA2170_checked_finite_model := PSCA_finite_model.
Definition PSCA2170_checked_kernel_model := concrete_finite_kernel.
Check PathEquiv_is_equivalence.
Check license_quotient_universal.
Check concrete_finite_kernel_exists.
Check complete_kernel_has_a_genuine_rule_step.
Check concrete_PSCA_has_nontrivial_transition_model.
Check prototype_protocol_Z4_quotient.
Check theorem_11_1_same_base_different_future.
Check rigid_filler_commutation_curvature_future_equivalence.
Check theorem_12_1_no_flat_normalization.
Check theorem_12_2_source_groupoid_reconstruction.
Check theorem_12_3_no_same_base_collapse.
Check theorem_12_3_general_structure_noneliminability.
Check theorem_13_1_no_effective_fully_abstract_encoding.
Check concrete_PSCA_has_nontrivial_transition_model.

(* Kernel-level audit: every headline theorem is closed under the global context. *)
Print Assumptions theorem_11_1_same_base_different_future.
Print Assumptions rigid_filler_commutation_curvature_future_equivalence.
Print Assumptions theorem_12_1_no_flat_normalization.
Print Assumptions theorem_12_2_source_groupoid_reconstruction.
Print Assumptions theorem_12_3_general_structure_noneliminability.
Print Assumptions theorem_13_1_no_effective_fully_abstract_encoding.
Print Assumptions concrete_PSCA_has_nontrivial_transition_model.
Print Assumptions concrete_finite_kernel_exists.
Print Assumptions complete_kernel_has_a_genuine_rule_step.
Print Assumptions concrete_PSCA_has_nontrivial_transition_model.
Print Assumptions PathEquiv_is_equivalence.
Print Assumptions license_quotient_universal.
Print Assumptions prototype_protocol_Z4_quotient.

